snowflakedb/snowflake-kafka-connector

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java
I was getting an error message along the lines of:
`topics: snowflake-sink is empty or invalid. It should match Snowflake object identifier`
I was confused because my topics property seemed to only have letters with underscores which is a valid identifier according to the documentation.
After checking the code, I found that it isn't validating the topics property, but it is validating the name property.
https://github.com/snowflakedb/snowflake-kafka-connector/blob/87041ff188a33c597d2949b2352b294c07f61f73/src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java#L219-L220
Updated the error message to have the right property it is validating.
> Fix the error message for name validation

- src/main/java/com/snowflake/kafka/connector/internal/Logging.java
- src/test/java/com/snowflake/kafka/connector/internal/LoggingTest.java
This commit fixes Logging.logMessage failing when some of vars are null.
This issue can be experienced, for example, in
https://github.com/snowflakedb/snowflake-kafka-connector/blob/949b5a168f3798be6f560ff1e2a8812023f8b83c/src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java#L359
> Fix logging format for null values

- src/main/java/com/snowflake/kafka/connector/records/SnowflakeAvroConverter.java
- src/main/java/com/snowflake/kafka/connector/records/SnowflakeAvroConverterWithoutSchemaRegistry.java
- src/main/java/com/snowflake/kafka/connector/records/SnowflakeConverter.java
- src/main/java/com/snowflake/kafka/connector/records/SnowflakeJsonConverter.java
This PR makes `ObjectMapper` in `SnowflakeConverter` non-static. This
prevents potential deadlock on classloading in Kafka Connect
(most likely, caused by https://issues.apache.org/jira/browse/KAFKA-7421).
See https://github.com/snowflakedb/snowflake-kafka-connector/issues/23
> Prevent deadlock on converter classes loading

- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/test/java/com/snowflake/kafka/connector/UtilsTest.java
checkVersion method doesn't work as for now, becouse of type in url it should comtain htts instead of http. As a result we see such WARNINGS in logs:
[SF_KAFKA_CONNECTOR] Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/com/snowflake/snowflake-kafka-connector/ (com.snowflake.kafka.connector.Utils:123)
> fix typo in maven url 

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
`.remove()` call in .forEach causes loop to be stuck. #123
> SnowflakeSinkServiceV1: iterate on a copy of all files in checkStatus()

- .github/workflows/End2EndTest.yml
- pom.xml
Major change:
- modified pom.xml to exclude kafka-connect-avro-converter 
- include kafka-schema-registry and kafka-avro-serializer 
The final jar size is 62MB.
Previous master build jar size is 37 MB
> SNOW-119851 Changed pom.xml to exclude avro converter

- .github/workflows/End2EndFullTest.yml
- test/apache_properties/schema-registry.properties
- test/build_apache.sh
- test/run_test.sh
- test/run_test_confluent.sh
Instead of using k8s we now use confluent platform to test, hopefully this is going to provide more stability over k8s in the full version test.
> Restructured all version test to use only one node for better stability

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java
No need to call get history if the number of files we wanted to check is zero.
> Reduce calls to ingest history

- src/main/java/com/snowflake/kafka/connector/records/RecordService.java
- src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java
With `org.apache.kafka.connect.json.JsonConverter`, integers are of type int64. When converting to JSON in `RecordService`, it will hit an NPE if value has no schema.
> Fix potential NPE in JSON conversion for int64 type without schema.

- src/main/java/com/snowflake/kafka/connector/records/SnowflakeAvroConverter.java
- src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java
Added a new option to the AVRO converter. By default this option is false so that we don’t have breaking change. 
"value.converter.break.on.schema.registry.error"="true"
This option, if set to true, will break the connector when there is error while fetching schema id from Schema Registry.
> SNOW-171230 Added a option to converter of whether break on schema registry error

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
This PR attempts to manage state around failure scenarios. 
Rather than try to force listStage in the exception handler, which is not safe, set state that indicates we are in a failure scenario. Let the cleaner thread sleep, then inspect the state and attempt to reset cleaner file in an exception safe way.
If resetCleanerFiles is not successful forceCleanerFileReset remains true and the main loop in the thread will continue. The loop will not progress past resetCleanerFiles() until it is successful.
> Force cleaner thread to reset files on error

- pom.xml
- pom_confluent.xml
- test/perf_test/pom.xml
Snowflake connector uses `snowflake-jdbc:3.11.1`.
There is a memory leak in `TelemetryService`, which has been fixed(https://github.com/snowflakedb/snowflake-jdbc/commit/c181874915bc0040fd6025f78374059250ee9ea5) in a newer version(`v3.12.3`) of Snowflake JDBC driver.
Assuming there are no breaking changes between `v3.12.3` and `3.12.10`, this PR upgrades `snowflake-jdbc` to the latest version `3.12.10`.
> Upgrade snowflake-jdbc to 3.12.10 to include SNOW-144823 memory leak fix.

- pom_confluent.xml
We had someone ask about whether this connector supports reading Protobuf data since the Confluent Hub description only mentions Avro and JSON. Since it's a Kafka Connect connector it should play nicely with any format as long as the right converter is provided, so we'd like to tweak the language a little to be more permissive and avoid giving the impression that this connector only works with two different types of input format.
> Tweak Confluent Hub description to be less restrictive in input formats

- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeStatus.java
Initial value of processed/flushed/committed/purged offset should be set to -1, because the offset stands for the last offset of the record that are at the status. When record with offset 0 is processed, processedOffset will be updated to 0. Therefore initial value should be set to -1 to indicate that no record have been processed.
> Fix a minor bug in telemetry

- src/test/java/com/snowflake/kafka/connector/internal/SinkServiceIT.java
Increased the time that the mocked api throws error to make sure cleaner is restarted. Therefor covering code that are in the cleaner restart process.
> SNOW-213553 Fixed flaky test on code coverage

- pom.xml
- pom_confluent.xml
Currently our test is distributed at the following maven life cycle: 
- `validate` 
- `compile`
- `test` 
- `package` - unit test
- `verify` - integrations test
- `install`
- `deploy`
We only need GPG signing when we push the build to Maven central, which uses command `mvn deploy`. Therefore, moving GPG signing from `verify` stage to `install` stage would remove GPG signing during integration test, but reserve GPG signing during `mvn deploy`. 
This modification is used to remove GPG signing error on Jenkins test.
> SNOW-220064 Modified pom

- .github/workflows/End2EndTestApacheAws.yml
- .github/workflows/End2EndTestApacheAzure.yml
- .github/workflows/End2EndTestConfluentAws.yml
- .github/workflows/End2EndTestConfluentAzure.yml
- .github/workflows/IntegrationTestAws.yml
- .github/workflows/IntegrationTestAzure.yml
- README-TEST.md
Split end to end and integration test, so that they can run in parallel. This speeds up the checkin process as tests are taking longer to run.
> Split end to end and integration test into different GitHub Action workflow

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java
- src/test/java/com/snowflake/kafka/connector/ConnectorIT.java
- test/apache_properties/connect-distributed.properties
- test/apache_properties/file-secrets.txt
- test/rest_request_template/travis_correct_string_json.json
If secrets in the config are read from a ConfigFileProvider, we cannot validate the config. Reading file path and do the validation is too complex and might result in permission error. So the simple solution would be to skip validation when passwords or passphrase is from file.
> SNOW-223109 read from secret files

- pom.xml
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeInternalStage.java
- src/test/java/com/snowflake/kafka/connector/ConnectorIT.java
- src/test/java/com/snowflake/kafka/connector/SinkTaskIT.java
- src/test/java/com/snowflake/kafka/connector/SinkTaskProxyIT.java
- src/test/java/com/snowflake/kafka/connector/internal/InternalStageIT.java
- src/test/java/com/snowflake/kafka/connector/internal/ResetProxyConfigExec.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- test/test_suit/test_string_json_proxy.py
- test/test_verify.py
Passing only proxy parameters in putwith cache instead of in JDBC connection
- Also added a test in internalStageIT
- Decouple SinkTaskIT and proxy tests
- Added few more helper method to reset the JVM parameters after every test
- Added exec maven goal to wipe out the proxy setting. 
- Added test in internalStageIT
- Decouple Proxy test in SinkTask to SinkTaskProxy
- Added exec-maven-goal which is used inside proxy end to end test to wipe out the JVM and JDBC config after the test has completed. (Inside clean method)
> [SNOW-242554] Calling JDBC's put api with proxy parameters

- .github/scripts/squid.conf
- .github/workflows/End2EndFullTest.yml
- .github/workflows/End2EndFullTestAzure.yml
- .github/workflows/End2EndTestApacheAws.yml
- .github/workflows/End2EndTestApacheAzure.yml
- .github/workflows/End2EndTestConfluentAws.yml
- .github/workflows/End2EndTestConfluentAzure.yml
- .github/workflows/IntegrationTestAws.yml
- .github/workflows/IntegrationTestAzure.yml
- .github/workflows/StressTest.yml
- pom.xml
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/main/java/com/snowflake/kafka/connector/internal/FileNameUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeInternalStage.java
- src/test/java/com/snowflake/kafka/connector/ConnectorIT.java
- src/test/java/com/snowflake/kafka/connector/SinkTaskIT.java
- src/test/java/com/snowflake/kafka/connector/SinkTaskProxyIT.java
- src/test/java/com/snowflake/kafka/connector/internal/InternalStageIT.java
- src/test/java/com/snowflake/kafka/connector/internal/ResetProxyConfigExec.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- test/rest_request_template/travis_correct_string_proxy.json
- test/test_suit/test_string_json_proxy.py
- test/test_verify.py
This includes following:
- Setup proxy server
- Run integration test and end to end test with proxy setup.
- Proxy username passwords are always admin and test.
- Integration test which is currently disabled but requires a proxy on local machine
Which was approved here: https://github.com/snowflakedb/snowflake-kafka-connector/pull/273
- Tested locally with newer version of snowpipe SDK jar. 
- Tested with github actions act: https://github.com/nektos/act
- It is able to create connector and also able to ingest a file in snowflake. 
- Waiting for tests to pass in workflow.
> Add integration and E2E test for proxy config with username and password

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/Utils.java
New release 1.5.2
Release Notes:
- Fixes bug for proxy configured kafka connector
- Newer version of Snowpipe SDK which support proxy configuration.
> Release Connector 1.5.2

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeInternalOperations.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeInternalStage.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryServiceV1.java
- src/test/java/com/snowflake/kafka/connector/internal/InternalStageIT.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- Added Java doc wherever I could to make code more readable.
- Added few log statements which will help for debugging.
- Refactoring a bit of code. (Sorry for mixing two, but it was too late when I decided I should have decoupled them)
- To make it easy, here are the changes:
- SnowflakeMetadataWithExpiration - Added `stageType` and made all fields `private final`. 
- `getStageType` - Make use of cache since cache has that information
- putWithCache API had a nested `try catch` -> Decoupled the mono-function to sub-functions based on the jobs and also added more logs which will help debug. `isValidCredential`, `refreshCredential`. 
- Removed `catch throwable` + `throw t`  which eventually `caught exception`. -> reduced it to just caught exception because Errors would have still be …
> GCS Put API Improvements + Refactoring

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/Utils.java
Release Notes: 
- BUG_FIX
- Added timeout while fetching latest kafka connector version from Maven. [SNOW-330782]
- Added thread safety around SimpleDataFormat while parsing dates and times. #302 [SNOW-295783]
- Fix handling of schemaless date objects. (#288) no-snow
- New Improvements
- More logs around retry and putting file into internal stage
- GCS Put API uses uploadWithoutConnection API - Should improve the latency. 
[SNOW-330782]: https://snowflakecomputing.atlassian.net/browse/SNOW-330782
[SNOW-295783]: https://snowflakecomputing.atlassian.net/browse/SNOW-295783
> Upgrade kafka to new version

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/Utils.java
Release Notes:
- Bumped up dependency (SF JDBC to latest version 3.13.3) 
- Mainly solves the problem around failures in putWithconnection API (Returns a failure if internal implementation around rest API throws a non 200 response)
> Release SF KC version 1.5.4

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java
Testing:
- I have locally tested this by overriding the snowpipe sdk jar. (Which is not yet released) Reason being I want to get an approval on this one so that I can release the SDK. 
- Here is what the userAgent looks like: 
- `SnowpipeJavaSDK/0.10.3 (Mac OS X 10.16 x86_64) JAVA/13 SFKafkaConnector/1.5.4 provider/SELF_HOSTED`
- I have added comments in the code which are self explanatory. 
- There are three allowed values to this configuration - `null/empty(equivalent to not provided)= UNKNOWN, SELF_HOSTED, CONFLUENT
PS:
- The test will fail now since I have not added the pom xml file. 
- Plan of action: Release snowpipe sdk, and push this with new version of sdk and see if the test passes. 
Here is how I have tested the local jar"
```
<repository>
<id>local-maven-repo</id> …
```
> Added provider config which is fed into userAgentSuffix for snowpipe for monitoring purpose

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
Initial Error:
```
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
at java.base/java.net.Socket.connect(Socket.java:608)
at net.snowflake.client.jdbc.internal.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
at net.snowflake.client.jdbc.internal.apache.http.impl.conn.DefaultHttpClientConnectionOperator.co …
```
> Fix bug: Passing in proxy props when opening a connection

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeKafkaConnectorException.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryBasicInfo.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeCreation.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeStatus.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeStatusMBean.java
- src/test/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeStatusMetricsIT.java
- src/test/java/com/snowflake/kafka/connector/internal/TelemetryUnitTest.java
- Here are the screenshots of the jconsole. 
- Here are the settings needed on client side - (Which is already documented here)
- https://docs.confluent.io/home/connect/monitoring.html#using-jmx-to-monitor-kconnect
- export JMX_PORT=PORT
- If running remotely:
- ``` KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=your.kafka.broker.hostname -Djava.net.preferIPv4Stack=true"```
> Added JMX metrics which will be exported to Mbean Server

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeStatus.java
- src/main/java/com/snowflake/kafka/connector/internal/metrics/MetricsJmxReporter.java
- src/main/java/com/snowflake/kafka/connector/internal/metrics/MetricsUtil.java
- src/test/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeStatusMetricsIT.java
- src/test/java/com/snowflake/kafka/connector/internal/TelemetryUnitTest.java
- Added histogram for buffer metric
- Improved unregistration code. 
- Lazily invoke remove metrics before registering them. (This can happen if there are rebalances) So rebalancing would start from all over again. 
- Fixed test
Example metric with 1000 records and 10 as buffer threshold.
> Add buffer metrics as Histogram

- src/main/java/com/snowflake/kafka/connector/internal/metrics/MetricsUtil.java
- Just for consistency since all other metric names have a `-` and not an underscore
> Rename latency metric for consistency

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeURL.java
- src/test/java/com/snowflake/kafka/connector/internal/SnowflakeURLTest.java
SNOW-445660
**Commit 1:**
- The string before google reformat didnt have + inside the matcher.
Changing this to a single line without a concatenation so that the
matcher string doesnt confuse with +
**Commit 2:**
- Adding a hyphen in account matcher group to support regionless URL along with tests.
> Regionless url regex support

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
Consider this scenario:
1. insertFiles has failed three times which results into no offsets being committed to return response of precommit. (Empty [HashMap](https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java#L291)) 
2. There is no restart/rebalance. 
3. InsertFiles API has been successful for newer offsets. 
4. Because we update the committedOffset, even though we would have unsuccessfully called insertFiles, our committedOffset pointer would have moved forward and we would skip those offsets.
> Do not update committed offset(In memory) and eventually to Kafka if insertFiles has failed

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/Utils.java
- Upgrade version to 1.6.1
A customer is using KC jar from confluent which is using confluent_pom.xml as opposed to being used from apache maven repo (pom.xml)
Also, upgrading the patch.
> Match pom for confluent with pom for apache maven repo

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
https://snowflakecomputing.atlassian.net/browse/SNOW-508731
`processing.guarantee=at_least_once/exactly_once`
Allow enable exactly once semantics property in the Kafka connector configuration file
> SNOW-508730  Introduce new config: processing.guarantee

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
I got this idea from https://docs.confluent.io/5.5.1/connect/managing/confluent-hub/kafka-connect-maven-plugin/kafka-connect-mojo.html
Which seems a better option.
> Change name to delivery.guarantee instead of processing.gurantee

- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskForStreamingIT.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
Rebalance [documentation](https://kafka.apache.org/11/javadoc/org/apache/kafka/connect/sink/SinkTask.html): 
- Close() will not invoke close on channel
- `close()` in sinktask is invoked before rebalance and `open()` is called. 
- It will also not clear the partitionsToChannel map. 
- One can argue that this map can grow but most of the times, same partitions are assigned and very rarely partitions are added. Even then this map cant grow more than no of partitions. 
- Made channel object in TopicPartitionChannel mutable. This is because TopicPartitionChannel object doesnt need to be wiped off when rebalance happens, but client is closed (Which results into channel being closed) So we have to open channel after rebalance. 
- Moved code for more readability. 
- Added test which replicates …
> SNOW-529753 Handle rebalance in SnowflakeSinkTask

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskForStreamingIT.java
- src/test/java/com/snowflake/kafka/connector/internal/SinkServiceIT.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
TLDR:
- No need to pass in `delivery.guarantee` into config.
- If they pass in, it should be EXACTLY_ONCE
- `AT_LEAST_ONCE` will error out. 
Logic:
- Cases where we need to be cautious. 
- The insertRows was called but precommit didnt send that because of a rebalance or shutdown. 
- In this case the offset can be resent back to KC and then we will discard it because we will also fetch it from Snowflake. 
- On a connector start, just fetch offsetToken for this channel. 
- The channel would have been already opened before. (from startTask)
- This value will be the source of truth and we will compare it with the incoming offset from Kafka.
> SNOW-536429 ☝️ exactly once for Streaming Ingest

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/main/java/com/snowflake/kafka/connector/dlq/KafkaRecordErrorReporter.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
- This is only available after 2.6.0
- Tested this with confluent 6.2.0
Background
- For snowpipe based implementation of KC, we used to send broken records coming from Native converters into tableStage. 
- Native converters are custom converters created for snowflake so that we can put records into tablestage. https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained/
- Take a look at `SnowflakeRecordContent` class to know more about what extra fields we add in converter logic before it reaches Kafka connector. 
- Also take a look at `SnowflakeConverter` abstract class and its implementation which essentially creates JSON bytes from kafka record and then send it to KC. 
Segway to why we dont need TableStage
- We can send records to DLQ. 
- DLQ is like any …
> Implement ErrantRecordReporter - kafka records from Sink Connector to DLQ

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
Refactor 1:
- Move openChannel inside TopicPartitionChannel since it can be used to re-open in case of failures. 
- Introducing a new library which implements retries, fallback and circuitbreaker. 
- https://github.com/failsafe-lib/failsafe
- I decided to not implement this because this can also be extended to various other retry mechanisms such as exponential and jitters. 
- Also, this library is very widely used. 
- Added tests to verify the behavior of retries. 
- TLDR: Only SFException will be retried and fallback to opening the channel. 
- No other exception will result into retry.
> SNOW-543664 offset token retries + Refactor to reopen channel on SFException 

- pom.xml
- pom_confluent.xml
I reviewed the change notes from 2.8.1 to 3.1.0 
https://kafka.apache.org/downloads
There are no significant changes in connect API. Hence this is safe to update.
> SNOW-551298  Use kafka connect-api 3.1.0

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/PartitionBuffer.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/SecurityTest.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
Error handling in insertRows + Logging/delivery to DLQ
- Add few configs for error handling. 
- [Here](https://www.confluent.io/blog/kafka-connect-deep-dive-error-handling-dead-letter-queues/) is how it will work. 
- error.tolerance = NONE 
- fail fast
- error.tolerance = ALL
- similar to on error continue. 
- can provide DLQ to send those records to DLQ (`errors.deadletterqueue.topic.name`)
- errors.log.enable = false by default
- can be used to log errors in log file. 
- Fallback for SFException
- No retry for insertRows. 
- Reopen the channel and reset kafka with offset found in snowflake. 
- Send retriableexception back from the put API. https://kafka.apache.org/31/javadoc/org/apache/kafka/connect/sink/SinkTask.html#put(java.util.Collection)
- Added test
- Will fix SNOW-545729 in …
> SNOW-530369 insert rows failure handling and delivery to DLQ

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/BufferThreshold.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingBufferThreshold.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/ConnectorIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingBufferThresholdTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
- Refactor code to validate buffer thresholds. 
- Set streaming buffer threshold to different values. 
- "Buffer.flush.time":"30" 
- Default: 30
- [Min,Max]: [1,30]
- "Buffer.count.records":"10000" 
- Default: 10,000
- [Min, Max]: [1, Inf] 
- "Buffer.size.bytes":"20_000_000"
- Default: 20,000,000 (~20MB)
- [Min, Max]: [1, Inf]
> Japatel snow 549265 flush time min 1 sec

- src/main/java/com/snowflake/kafka/connector/internal/PartitionBuffer.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
Bug:
No need to check for count of records in buffer == (lastOffset number - firstOffset number + 1)
This will not be true when there are bad records sent to Kafka but we would not buffer those bad records resulting into incorrect exception being thrown rather than inserting remaining rows. 
Test included
> NO-SNOW: BUGFIX - Remove unnecessary check for buffer count and add a test

- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
Found this could be helpful. I wasnt able to figure out why the insertRows API was failing.
> Add a debug statement for insert rows failure

- .github/workflows/End2EndFullTest.yml
- .github/workflows/End2EndFullTestAzure.yml
- .github/workflows/End2EndFullTestGCS.yml
- .github/workflows/End2EndTestApacheAws.yml
- .github/workflows/End2EndTestApacheAzure.yml
- .github/workflows/End2EndTestApacheGCS.yml
- .github/workflows/End2EndTestConfluentAws.yml
- .github/workflows/End2EndTestConfluentAzure.yml
- .github/workflows/End2EndTestConfluentGCS.yml
- .github/workflows/IntegrationTestAws.yml
- .github/workflows/IntegrationTestAzure.yml
- .github/workflows/IntegrationTestGCS.yml
- .github/workflows/PerfTest.yml
- .github/workflows/StressTest.yml
- pom.xml
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/internal/BufferThreshold.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/records/RecordService.java
- src/test/java/com/snowflake/kafka/connector/internal/SinkServiceIT.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
- test/setup_k8s.sh
- Transform record only when records are ready to invoke insertRows API.
- Move around code to only buffer kafka record.
- Add utility method to find out size of kafka record.
PS:
- Suggestions are welcomed for finding out size of kafka record. I couldnt find the best possible way hence this hack. 
- The size of this record is a bit more than when we were just calculating the entire row size. (In Snowpipe Ingestion)
- But this size is still lesser than both row + kafka record combined. 
- Please note, we have to store Kafka record to be able to send it to kafka DLQ. 
I did the testing:
- Approximate number of records buffered in snowpipe and streaming snowpipe case is same even though the objects buffered in memory are different. 
Most recent commit:
- Process the record and find out the …
> Japatel snow 552576 avoid extra memory buffer

- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
I had forgotten to change the default time to 10 seconds. 
(I had done the cost comparison for 10 seconds too, which was still cheaper than 120 seconds snowpipe for trickle)
I will also make changes in docs, and I think it is still fine to go with 10 seconds even if docs are not updated by the time we release (30 seconds)
> no-snow set default flush time to 10 seconds

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/Utils.java
- Bumping up minor version. 
- Private Preview only. 
- Not all customers will have this. 
- Request to enable. 
As simple as adding at least two more properties. (Documentation update on Snowflake Docs, coming out soon)
```
"snowflake.ingestion.method": "snowpipe_streaming",
"snowflake.role.name": "<role_name>",
```
> Release version 1.8.0 - Private Preview for Streaming Snowpipe + KC 😉  🤩  

- pom.xml
- pom_confluent.xml
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
Release awaited KC with newer version of ingest SDK. 
Version 1.8.1 was already bumped, but we waited for this release to happen.
> Upgrade Ingest SDK to 1.0.2-beta.4 for KC release 1.8.1

- .github/workflows/StressTest.yml
- test/test_suit/test_pressure.py
- test/test_suit/test_pressure_restart.py
- test/test_verify.py
This Change:
- Required to identify if we can support future versions of Confluent Platform. 
- End to End tests are already passing, these two tests were the most flakiest. 
- Refactor stress tests to different functions so as to not run along
with End to End Tests
- Stress Tests wont run on master push or PR, will only run once every
week on saturday (Check Schedule in StressTest.yml file)
Future Improvements: (Filed JIRAs)
- Run a lot of Job Pre Steps inside a docker container and just pull that image. 
- Refactor test suits to a map instead of a list of Tests and List of True False, makes it easier for reading and enabling/disabling tests.
> SNOW-645776 Part 2 Stress Tests run on Confluent's Different Versions Against Different Cloud

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
Customer stated their logs was bloating due to a lot of Task logging. 
Changed the log level to debug and removed the initial log statement for multiple methods
https://github.com/snowflakedb/snowflake-kafka-connector/issues/517
> [SNOW-725923] Reduce amount of Task logs

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/test/java/com/snowflake/kafka/connector/SinkTaskIT.java
- src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskForStreamingIT.java
Fixing previously broken IT from a logging change I introduced. Changes log messages and levels we use to validate functionality.
Also using debug instead of info for the tasks tart message, missed that in the last change (probably because i hadn't run the tests)
> Fix broken logging IT

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
The jvm.nonProxy.hosts parameter can be added to the connector's configuration file and is the equivalent to the JVM argument -Dhttp.nonProxyHosts. If a user provides that parameter and the connector runs in a JVM where -Dhttp.nonProxyHosts was set, then we will merge the two lists of hosts. In the future, we'll want another method of adding proxy configurations without resorting to System.setProperty() calls
> [SNOW-726924] Add New jvm.nonProxy.hosts Parameter and update JDBC to 3.13.23

- src/main/java/com/snowflake/kafka/connector/internal/ingestsdk/StreamingClientManager.java
- src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskForStreamingIT.java
- src/test/java/com/snowflake/kafka/connector/internal/ingestsdk/StreamingClientManagerTest.java
Client creation logic creates one extra client due to the way the for loop is configured. Made test stricter by exposing the client count.
And fix an IT test that was missed in the last PR.
Thanks @sfc-gh-japatel for catching both of these!
> Fix client off by one issue

- .github/workflows/End2EndTestApache.yml
- .github/workflows/End2EndTestConfluent.yml
- .github/workflows/IntegrationTest.yml
- .github/workflows/StressTest.yml
- pom.xml
- pom_confluent.xml
- test/test_suit/test_schema_mapping.py
- test/test_suit/test_schema_not_supported_converter.py
Background:
- After upgrading ingest sdk to 1.0.3-beta, GCS tests started failing. 
- Above version uses jdbc 3.13.18
- We have our own native jdbc dependency at 3.13.23. 
- Intellij bytecode never showed code corresponding to 3.13.23 and always picked up from 3.13.18 (From Ingest SDK)
Root cause:
- Previously the jdbc dependency was defined after ingest SDK and APPARENTLY ORDERING MATTERS
Solution:
- Exclude jdbc from ingest SDK. 
- Define our own jdbc version in Connector. 
Next steps:
- Fix JDBC version in Ingest SDK to use 3.13.23 instead of 3.13.18
Few more changes:
- Use fail fast strategy to not kill other running tasks in matrix if one fails. We want all of them to run parallely. 
- Fix broken tests after allowed data type formats changed in latest version of ingest SDK. 
**MAVEN …
> Modify pom.xml to use jdbc defined in connector and not from ingest sdk

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/records/RecordService.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
- Why as possible
- It is possible we dont have connection object everywhere, so in that case, we will not be able to send telemetry to Snowflake
Part 1:
- Use telemetry Service wherever possible to send exceptions to Snowflake
Future PRs:
- We will annotate whether Snowpipe Streaming is used or Snowpipe to distinguish. 
- Channel usage telemetry - For example send data for channel open/close.
- Add alerts later on Snowflake Side.
> SNOW-758111 Use telemetry service for all exceptions wherever possible

- test/test_verify.py
- Revi will push her change but these delivery tests are getting very flaky. 
- End2End tests are running under 15 mins. Down from 45 mins in each suite. 
- https://github.com/snowflakedb/snowflake-kafka-connector/actions/runs/4439592229/jobs/7792262057?pr=577 
- Helps reducing the noise https://github.com/snowflakedb/snowflake-kafka-connector/pull/573
> Disable delivery guarantee tests

- pom.xml
- pom_confluent.xml
- I was struggling to run only integration test with our setup from a host machine against preprod12
- I researched about how this is running from our KC. 
- From https://maven.apache.org/surefire/maven-failsafe-plugin/ it is mentioned that failsafe should be used for Integration Test and surefire is only used for unit testing. 
This change will help in following way:
- Run below to execute only Unit Tests
`mvn clean test`
- You can execute below command to run the tests (both unit and integration)
`mvn clean verify`
- In order to run only Integration Tests, follow
`mvn failsafe:integration-test`
- Or skip unit tests
`mvn clean install -DskipUnitTests`
- Run single test IT test
`mvn -Dit.test=TopicPartitionChannelIT verify`
- Skip bunch of tests which are failing and requires some extra …
> NO-SNOW Best practice: Use fail-safe plugin for IT tests

- .github/workflows/End2EndFullTest.yml
- .github/workflows/End2EndFullTestAzure.yml
- .github/workflows/End2EndFullTestGCS.yml
- .github/workflows/End2EndTestApache.yml
- .github/workflows/End2EndTestConfluent.yml
- .github/workflows/IntegrationTest.yml
- .github/workflows/StressTest.yml
- README-TEST.md
- README.md
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/records/RecordService.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
- test/build_runtime_jar.sh
- test/run_test_confluent.sh
- test/test_verify.py
- Catch issues before releasing a zip in Confluent Hub
- Use pom_confluent.xml in our tests. We only used pom.xml until now and no way to check the diff between those two. 
- For private key which are encrypted, we have to deploy fips jar to confluen setup, this test would have caught that. 
- Rename build_apache.jar with build_runtime_jar
- Use pom_confluent.xml in Running End to end test against Confluent
- Pass in confluent argument when we want to use confluent as kafka runtime. 
- Add description in sh script. 
- pom_confluent uses https://docs.confluent.io/platform/current/connect/kafka-connect-maven-plugin/site/plugin-info.html plugin to create a zip file which gets released to Confluent Hub. 
Update: [For confluent tests]
- For all versions, we point plugin path to the zip file we …
> SNOW-760171 Use pom_confluent.xml in running confluent tests

- .github/workflows/End2EndTestApache.yml
- .github/workflows/End2EndTestConfluent.yml
- .github/workflows/IntegrationTest.yml
- .github/workflows/StressTest.yml
- pom.xml
- pom_confluent.xml
Also upgrade maven plugin versions to a more recent versions to reduce flakiness in Github Action
- Helps reduce the build time of our library on Github Action. 4x improvement
- Master run for build: https://github.com/snowflakedb/snowflake-kafka-connector/actions/runs/4451294967/jobs/7817781250 (12 mins)
- Current run for build: https://github.com/snowflakedb/snowflake-kafka-connector/actions/runs/4451509883/jobs/7818250333?pr=579 (3 mins)
- Stress tests took 1hr to run before, now only 30 mins. 
- Faster response time for merge gates and pushing the PR to master.
> NO-SNOW Use maven Cache - 4X improvement in runtime of Github Actions for builds

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/BufferThreshold.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/ConnectorIT.java
Collect all invalid parameters and error messages to log and throw an exception at the end
Changes: 
- Replaced isConfigValid boolean with invalidConfigParam hashmap
- Changed most of the 'validateX' methods to return the list of invalid params and messages
- Added additional assert to config tests to check for the required invalid params
> [SNOW-659469] List all invalid parameters 

- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
Apologies, I accidentally deleted the `@Test` in this previous PR https://github.com/snowflakedb/snowflake-kafka-connector/pull/586. Reenable these tests
> Reenable accidentally disabled config tests from PR 586

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryService.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
Adds a parameter to enable one client optimization (all partitions and tasks pointing to one client). This param is currently unused, but will be used in later PRs.
> One client change 1/3: add parameter to enable one client optimization

- .github/workflows/End2EndTestApache.yml
- .github/workflows/End2EndTestConfluent.yml
- .github/workflows/IntegrationTest.yml
- .github/workflows/PerfTest.yml
- .github/workflows/StressTest.yml
- test/run_test_confluent.sh
- test/test_suites.py
- test/test_verify.py
- Refactor test suites to make it easier for enabling and disabling a test. 
- There are 30 tests right now and I cant tell whether a test is enabled or disabled in confluent and apache. 
- Disable two failing tests - SNOW-774533 for re-enabling them
- One is DLQ test which suddenly started failing.
- I dont have ideas on why this is failing. Will fix that later since other PRs are blocked. 
- It is very much possible server side we changed something because ingest SDK is unchanged. 
- Other is a test containing decryption of fips
- My suspicion is maven caching has issues because fips library does weird checksum checks of jar files. 
- Even after deletion of cache, I saw failures so something very weird is happening.
- Add while loop ending method in DLQ consumption. 
- Disable maven …
> NO-SNOW Refactor Test suites  + Disable failing tests to unblock other PRs

- test/build_runtime_jar.sh
- test/test_suites.py
- test/test_verify.py
- Currently, the plugin path has Snowflake jar and zip built from confluent maven. For confluent runtime, we only need zip created by build_runtime_jar deployed to plugin path. (Unzipped)
- There is a fips exception caused by two different versions of fips identified by JVM since fips does sha256 on every fips associated jar available on classpath. 
Simply have different runtime jars deployed for apache kafka and confluent kafka. 
- Apache kafka will have plugin jar + fips installed from maven. 
- Confluent Kafka will have every needed jar in the zip file. (Try it out by downloading zip from confluent hub and checking lib directory)
> SNOW-774533 Enable Json & Proxy Test - Bug in setting up Confluent Tests

- src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
- No test, relying on JDBC tests. https://community.snowflake.com/s/article/JDBC-Driver-Release-Notes
- We will test later on our privatelink setup which is broken right now since qa3 is decomissioned.
> SNOW-480523 Fix breaking change in upgrade to JDBC 3.13.25

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/IngestionMethodConfig.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeTelemetryServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryBasicInfo.java
- src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryPipeCreation.java
- src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryPipeStatus.java
- src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryService.java
- src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryServiceV1.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
- Also add default ingestion method in all msg in telemetry. Using ordinal to save some bytes. 
- Sending fatal errors in TopicPartitionChannel. 
- Not sending all channel reopen events since that data is already present in Snowflake EventLogger.
> Add telemetry for fatal errors in TopicPartitionChannel

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
Readding #533 
The jvm.nonProxy.hosts parameter can be added to the connector's configuration file and is the equivalent to the JVM argument -Dhttp.nonProxyHosts. If a user provides that parameter and the connector runs in a JVM where -Dhttp.nonProxyHosts was set, then we will merge the two lists of hosts. In the future, we'll want another method of adding proxy configurations without resorting to System.setProperty() calls
- Jay - Rebasing master, picking 3.13.25 and other changes.
> [SNOW-726924] Add New jvm.nonProxy.hosts Parameter - Undo Revert 

- .github/workflows/End2EndTestConfluent.yml
- This will reduce our flakiness of test failures. 
- https://docs.confluent.io/platform/current/installation/versions-interoperability.html
- We will also update docs.
> SNOW-803249 Remove confluent 5.5.11 since it is no longer supported

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/test/java/com/snowflake/kafka/connector/SinkTaskIT.java
Most SnowflakeSinkTask from debug to info for debugging purposes. Also update the precommit log to include the number of partitions instead of record count. Note that this may increase log size, however they are very nice to have for debugging.
Example log:
`[SF_KAFKA_CONNECTOR] Successfully called PUT with 10000 records, executionTime: 1643 ms`
`[SF_KAFKA_CONNECTOR] Successfully called PRECOMMIT on all 1 partitions, safe to commit 1 partitions, executionTime: 744 ms`
> Revert kafka put and precommit log message to info

- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceFactory.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- Here is what the connection object is used for: [Only for Snowpipe Streaming]
- DB existence checker. 
- Schema existence checker.
- CreateTable
- Alter table 
Do you need test for this change?
- Existing tests uses a user and a uses a default role. [Check profile.json]
- Verifying existing tests passes is enough. 
- ConnectionServiceIT is one test which verifies this code path. 
- It's not worth adding the another profile.json and modifying the existing tests to use a new user/role. 
- Manual tests: Ran a manual test in sfctest0 account with a new role and a new user. Also ran a test which revoked an insert privilege from this role and it resulted into channel open error. 
Can anything go wrong with this change?
- Yes, if the default role of the user has more privileges than the role …
> SNOW-826772 Unification of Snowflake role and user for Snowpipe Streaming

- pom.xml
- pom_confluent.xml
- Update google guava for CVE: https://avd.aquasec.com/nvd/2023/cve-2023-2976/
- It says 32.0.1 is better suited than 32.0.0
- Also requested from confluent.
> no-snow update Google guava

- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
Benefits:
- Performance improvement since we will not be waiting for channels to get closed. Currently, channel.close().get() is a blocking call. 
- We anyways reopen the channel during open partition. 
- I have seen significant improvements in closing of partitions in terms of latency. This will be visible when more partitions are assigned to a task. (Happens when customers uses a lot of topics in their connector)
- Less number of exceptions in close API call if previous call to insert rows resulted in failure. 
Tests:
- Existing tests are enough. 
Here are few examples of what we gain:
- Test setup: Create a single snowflake connector starting with one topic and 4 tasks. Keep on adding 10 datagen connector adding data to 10 topics and also modify the existing snowflake connector with …
> SNOW-811265 Do not close channel on rebalance

- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
This reverts commit 52f0a8a821f748b0715f49462a67b4b5cf1800fe.
After careful consideration, we will revert "not closing channels" before a rebalance. i.e we will continue to close channel in `close()` API of SinkTask. 
Closing the channel makes the behavior a bit more deterministic, closes resources and now that we have one client enabled, closing of channels wouldn't take a long time. (Probably only the first channel will take time but not subsequent)
> Revert "SNOW-811265 Do not close channel on rebalance (#651)"

- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
those which are part of close API
Added test with comments which fails in previous versions. 
TLDR:
- We have observed close API from kafka connect only closing certain partitions assigned to a task. 
- Until now, we clear entire map which can have data in its buffer. Even though we reopen the channel and reset offset in kafka, the in memory variables are advanced and if Kafka connect send those offsets again we ignore and skip adding it in buffer. 
- Clearing entire map also affects the put latency in which it reopens the channels. Kafka connect adheres to the contract that if a partition is closed, it will not send data for that partition, but since we are clearing entire map, we are not sticking to that protocol. 
- The IT test mimicks/mocks this behavior. 
- Here are the triggering …
> SNOW-811265 Not clearing entire map of partitionToChannel, only remove

- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskStreamingTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
#702 
- We need this when they want to use two connectors with same topic name to ingest into two different tables. 
- Current logic will ping pong the open-close channel API between two connectors. 
- Nothing changes in pipe name in Snowpipe Kafka
Fixed tests.
> [NO-SNOW] Prefix with channel name with connector name

- .github/workflows/IntegrationTest.yml
- .github/workflows/PerfTest.yml
Python 3.6 is end of life and causing integration test github action runs to fail. Upgrade to 3.9 (similar to other [tests](https://github.com/search?q=repo%3Asnowflakedb%2Fsnowflake-kafka-connector%20setup-python&type=code))
> GH actions tests upgrade python from 3.6 to 3.9

- src/main/java/com/snowflake/kafka/connector/records/RecordService.java
- test/rest_request_template/test_string_json_ignore_tombstone.json
- test/test_suit/test_schema_evolution_json.py
- test/test_suit/test_schema_evolution_json_ignore_tombstone.py
- test/test_suit/test_snowpipe_streaming_string_json.py
- test/test_suit/test_snowpipe_streaming_string_json_ignore_tombstone.py
- test/test_suit/test_string_json.py
- test/test_suit/test_string_json_ignore_tombstone.py
Snowflake converters and community converters convert empty string records different. Snowflake converters treat "" as a valid record, community converters treat "" as a tombstone record. Use python None (null) instead of empty string to accurately test tombstone ingestion
Discussed offline with @sfc-gh-tzhang to use None instead
> [SNOW-916052] Use python None instead of empty string for tombstone e2e tests

- pom_confluent.xml
- src/test/java/com/snowflake/kafka/connector/internal/TombstoneRecordIngestionIT.java
- test/perf_test/pom.xml
Received email about https://nvd.nist.gov/vuln/detail/CVE-2023-39410 so update our pom.xml accordingly
Snyk [updated our main pom](https://github.com/snowflakedb/snowflake-kafka-connector/commit/3021c2b1ccd315c0b59aa40fb7d3821c7fcc299a), but not our confluent or perf test pom. Will follow up to see if we can get snyk to scan all the poms
> [SNOW-934984] Update Avro version for security vulnerability

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskStreamingTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
- test/rest_request_template/test_snowpipe_streaming_channel_format_v2.json
- test/test_suit/test_snowpipe_streaming_channel_format_v2.py
- test/test_suites.py
PROD-39429
This Commit is adding a parameter to https://github.com/snowflakedb/snowflake-kafka-connector/commit/3bf9106b22510c62068f7d2f7137b9e57989274c and is also reverting the behavior. 
i.e If this commit is pushed and is in release branch, the behavior of determining the `channelName` is reverted. (Contains only topic name and partition number)
Users will have to enable the parameter `snowflake.enable.new.channel.name.format` (set to true) to have connector name in their channel name. 
1. For customers on 2.1.0 where [this](3bf9106b22510c62068f7d2f7137b9e57989274c) change was introduced, we are asking you all to be cautious and look for duplicates. Chances of duplicates are very slim but still possible. We would encourage you all to upgrade to next patch version which has this revert …
> PROD-39429 Add parameter for connector name in channel name:

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SchematizationUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/records/RecordService.java
- src/main/java/com/snowflake/kafka/connector/records/SnowflakeRecordContent.java
- src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java
- src/test/java/com/snowflake/kafka/connector/records/HeaderTest.java
- src/test/java/com/snowflake/kafka/connector/records/RecordContentTest.java
- test/rest_request_template/travis_correct_schema_evolution_avro_sr_logical_types.json
- test/test_suit/test_schema_evolution_avro_sr_logical_types.py
- test/test_suites.py
There're 10 AVRO logical types listed in https://avro.apache.org/docs/1.11.0/spec.html#Logical+Types and we're able to support 4 of them, the mapping is as below:
- date -> DATE
- time-mills -> TIME(6)
- timestamp-mills -> TIMESTAMP_NTZ(6)
- decimal -> VARCHAR (We can't do NUMBER because we could have precision bigger than 36)
We can't do for the rest of 6 types because that's not supported by ConnectSchema, see [code](https://github.com/a0x8o/kafka/blob/54eff6af115ee647f60129f2ce6a044cb17215d0/connect/api/src/main/java/org/apache/kafka/connect/data/ConnectSchema.java#L68) for more detail. We need to find another way to support other logical types or any sources (like Debezium).
> SNOW-938038: Support AVRO Logical Types

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
- src/test/java/com/snowflake/kafka/connector/internal/InternalStageIT.java
Upgrade JDBC to 3.14.3. 
Modify some tests since v3.13.31 is throwing NPE.
> SNOW-913746 upgrade jdbc 3.14.3 

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/ChannelMigrateOffsetTokenResponseDTO.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/ChannelMigrationResponseCode.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskStreamingTest.java
- src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java
- src/test/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1Test.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
- test/rest_request_template/test_snowpipe_streaming_channel_migration_disabled.json
- test/test_suit/test_snowpipe_streaming_channel_migration_disabled.py
- test/test_suites.py
PR https://github.com/snowflakedb/snowflake-kafka-connector/pull/750 but pushed in main. 
Copying it as is. 
This is a long term implementation for potential data duplication introduced because of a new channel name format. 
- It is about moving away for customers who might have onboarded to new channel format which was introduced in version 2.1.0 (Now de-listed)
- We will stick to old format for new customers running this for the first time. 
- Renamed channelName to channelNameFormatV1 and introduced `channelNameFormatV2`
Added tests in `TopicPartitionChannel` and `TopicPartitionChannel`
Notes:
- This PR is opened against [japatel-SNOW-971412-release-2-1-1-ready](https://github.com/snowflakedb/snowflake-kafka-connector/tree/japatel-SNOW-971412-release-2-1-1-ready) which is going to be …
> PROD-39429 Implement migrate sys func from new channel(Format V2) to old channel (V1) - Push to Main

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java
- src/test/java/com/snowflake/kafka/connector/ConnectorIT.java
Copy @swehner 's [PR](https://github.com/snowflakedb/snowflake-kafka-connector/pull/747) for github actions runs. 
@sfc-gh-xhuang please confirm that CLA was signed
I'm trying to use different config providers in my snowflake connector, but get an error during validation because the snowflake private key is not valid.
This is because validation seems to receive the raw config values (not running through configProviders which seems iffy).
In any case there was already a workaround to support ${file: as a config provider value and to skip validation. I've extended it to include any configProvider with a different name.
Fixes issue https://github.com/snowflakedb/snowflake-kafka-connector/issues/748
> [external contributor] Support config providers in validation by @swehner

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProperties.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientHandlerTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientPropertiesTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
When schematization is enabled, we're inserting row by row in order to preserve the original order of the batch, this leads to an issue if the data validation for each row is slow, we might end up with many small files since the SDK flushes every second. Exposing the MAX_CLIENT_LAG helps solve this issue shoer term. Longer term, it would be good if we can avoid inserting row by row for schematization.
- Support a new configuration `snowflake.streaming.max.client.lag` in KC. Instead of adding a new configuration, i update the blob version config since we don't support ARROW in the new SDK, adding less code is always better
- Extend the `StreamingClientProperties` to use different client if the `parameterOverrides` is also different
- Corresponding test cases added
> NO-SNOW: Expose the Ingest SDK MAX_CLIENT_LAG configuration in KC 

- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- Validates that the given parameter for SNOWPIPE_STREAMING_MAX_CLIENT_LAG is a long
- Fixes a max lag IT
> Add authentication for max lag parameter and fix IT

- src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
java.lang.NoClassDefFoundError: Could not initialize class net.snowflake.client.jdbc.internal.apache.arrow.memory.RootAllocator occurs when the JDBC driver tries to process the result of the offset migration query. This is a known long-standing issue in the JDBC driver so a workaround is introduced with this fix.
> SNOW-989387: Fix for java.lang.NoClassDefFoundError

- test/test_data/protobuf/pom.xml
it seems the version of `protoc` tool was out of sync with the jar used to compile the generated code .
upgrading jar to latest version solved the issue of missing method.
> resolves issue with generating and building java libary

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/Utils.java
!! v2.2.0 will not be released until beginning of February 2024 !!
This commit updates the version to v2.2.0 which will contain everything before this commit in the master branch
> Update version to 2.2.0 for release

- .github/pull_request_template.md
One of the action items from PROD-39429 was to include PR templates and checklist before committing a code. 
I have followed snowflake repo but added few checklists which applies to our KC repo. 
Irony is, I cant see the template in this PR.
> PROD-39429 Add PR template

- README-TEST.md
- test/run_test_apache.sh
- test/run_test_confluent.sh
- test/test_suites.py
- test/test_verify.py
This PR enables running subset of e2e tests `./run_test_apache.sh 2.5.1 apache_properties false false --skipTests --tests=TestStringJson,TestAvroAvro` 
There is still huge space for improvement here:
- turn all parameters from non-named into named for both Shell and Python
- add decent named parameters parsing for Shell (like https://unix.stackexchange.com/questions/331522/how-do-i-parse-optional-arguments-in-a-bash-script-if-no-order-is-given)
- handle default arguments values
- skip unnecessary downloading for local development
Anyway let's do it step-by-step. This PR alone will save us hours in long term.
> Run subset of e2e tests

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProperties.java
- src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryService.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientPropertiesTest.java
- test/rest_request_template/test_streaming_client_parameter_override.json
- test/test_suit/test_streaming_client_parameter_override.py
- test/test_suites.py
SNOW-1117446
Instead of having a new property in KC config for every overridden key value pair, we input a comma separated KV pair. 
This review is ***URGENT*** priority
Imagine customer upgrading to new version and rolling back to older version. Will there be any concerns?
[X] Backward compatible - They will have to remove the new config since we dont validate this new config in older versions. 
[ ] Forward compatible
-->
Reviewers:  Every review must have at least two reviewers for bug fixes, GA'ed component. One reviewer is enough for test only, doc changes.
- Minimum # of Required Reviewers - **Two** for Improvements and Bugfixes - Toby, Tyler, Revi
- Educational purposes - @ Warsaw Team
> SNOW-1117446 Snowpipe Streaming client provider map

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProvider.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2StopIT.java
- test/perf_test/pom.xml
https://snowflakecomputing.atlassian.net/browse/SNOW-1049869
KC does not call `close()` method on streaming ingest client instance when `stop()` is called on task restart or termination. It results in some internal threads not being closed and probably a memory leak as well. 
If one client optimization is enabled it is not a big deal. Client will be reused on task restart and will leak only on task termination which is rare.  Max 10000 clients are cached so no more threads will leak.
When client optimization is disabled then we will experience a massive thread leak as new streaming ingest client is created on every task restart.
> SNOW-1049869 Cleanup streaming ingest threads when SinkTask stop() is called

- test/rest_request_template/nullable_values_after_smt.json
- test/rest_request_template/travis_correct_nullable_values_after_smt.json
- test/test_suit/test_nullable_values_after_smt.py
- test/test_suites.py
SNOW-1055524
Implementing an e2e test with an SMT that can return a nullable value.
To keep things simple, `org.apache.kafka.connect.transforms.ExtractField` has been used. By filling in an optional value for half of the events only we achieve alteration between non-nullable and nullable values.
> SNOW-1055524 E2E test with nullable SMT

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/internal/PipeProgressRegistryTelemetry.java
- src/main/java/com/snowflake/kafka/connector/internal/ProgressRegistryTelemetry.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/StageFilesProcessor.java
- src/test/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1Test.java
- src/test/java/com/snowflake/kafka/connector/internal/StageFilesProcessorTest.java
- src/test/java/com/snowflake/kafka/connector/internal/StageFilesProcessor_FileCategorizerTest.java
SNOW-1019628
This PR addresses reported issue of cleaner not properly handling file cleanup - in some scenarios, files will be kept in staging area for as long as there is no message in the topic. 
This change modifies the file handling algorithm - it no longer depends on the first record to be received to start - it will start automatically for each partition. 
To enable this new cleaner, provide following configuration entry to your connector config:
`"snowflake.snowpipe.v2CleanerEnabled": true`
Core processing logic happens in ` StageFilesProcessor::trackFiles` 
This method is run in a worker thread. The only way to communicate with the cleaner, is through `ProgressRegister` interface, which allows adding new ingested files for tracking in a thread safe manner.
> SNOW-1019628 update file cleaner for snowpipe ingest

- test/rest_request_template/nullable_values_after_smt.json
- test/test_suit/test_nullable_values_after_smt.py
- test/test_suites.py
SNOW-1055524
mplementing an e2e test with an SMT that can return a nullable value for a Snowpipe based connector.
To keep things simple, org.apache.kafka.connect.transforms.ExtractField has been used. By filling in an optional value for half of the events only we achieve alteration between non-nullable and nullable values.
> SNOW-1055524 E2E SMT for a Snowpipe based connector

- .github/workflows/End2EndTestApache.yml
- test/run_test_apache.sh
SNOW-1269024 - adding verification on different versions of JRE
Building and unit testing process remains the same (Java8) but e2e testing is run on three different versions of JAVA: 8, 11 and 17. This means that there are 3 times more testing jobs, but they all run in parallel, hence total run time should remain ~the same. 
*normal* 
Longer test runs
> SNOW-1269024 Installing multiple Java versions for test purposes

- .github/workflows/IntegrationTest.yml
- src/test/java/com/snowflake/kafka/connector/builder/SinkRecordBuilder.java
- src/test/java/com/snowflake/kafka/connector/records/RecordContentTest.java
SNOW-1348656 Kafka Processing error not sent to DLQ correctly.
Initial refactoring:
- migration to JUnit5
- removing code duplication with `@ParameterizedTest`
- adding builder for `SinkRecord`
> SNOW-1348656 Migrate RecordContentTest to JUnit5

- src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
SNOW-1369271
[StreamingIngestChannel can throw an SFException](https://github.com/snowflakedb/snowflake-ingest-java/blob/master/src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java#L285) when calling close. That causes connector tasks to be stopped. 
Ignoring `SFException` when channels are invalid remediates this issue. 
This review is **high** priority
> SNOW-1369271 Ignore SFException when closing a channel

- .github/CODEOWNERS
NO-SNOW
As a part of project handoff, we need to change CODEOWNERS. My team feels confident that we can take over full ownership.
> Transfer ownership of project in CODEOWNERS file. Change streaming-ingest to snowpipe kafka team

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
SNOW-1061848
This is my second attempt to remove the buffering from a quite tightly convoluted piece of code in the `BufferredTopicPartitionChannel` class.
To reduce the extent of changes, and make it easily comparable to the old implementation, the PR is prepared in 3 steps (1 step is 1 commit).
1. DirectTopicPartionChannel is just a clone of BufferrredTopicPartitionChannel - you can skip browsing this commit.
2. My attempt to delete all buffers-related classes and make the code work again. Any doubts were solved by adapting Revi changes from the PR https://github.com/snowflakedb/snowflake-kafka-connector/pull/735
3. Fix of unit tests to make them green
The current implementation is validated with:
- `TopicPartitionChannelTest` - all green
- some of `TopicPartitionChannelIT` -however it …
> SNOW-1061848: DirectTopicPartitionChannel - copy of the old implementation with removed buffer

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
…make TestSnowpipeStreamingSchemaMappingDLQ passing
SNOW-1475664
Fixing `TestSnowpipeStreamingSchemaMappingDLQ` test by moving some part of additional validation from BufferedTopicPartitionChannel.
> SNOW-1475664: Move additional error handling from BufferedTopicPartitionChannel to fix E2E test

- src/main/java/com/snowflake/kafka/connector/internal/streaming/BufferedTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
SNOW-1514185
The change applies to channel reopen logic. The process used to consists of 3 steps:
- reopen the channel
- fetch the offset from the channel
- reset internal buffer
- rest offset in Kafka
If any of the steps 2-4 fails during `getOffsetSafeToCommitToKafka` the error will be ignored in [SnowflakeSinkTask::preCommit](https://github.com/snowflakedb/snowflake-kafka-connector/blob/15df7115dc26a2ad015f8486d6dd3f48a460e525/src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java#L347-L349)
After the change the channel is assigned to the TopicPartitionChannel after all the steps are done.
> SNOW-1514185: Do assign the reopened channel unless kafka offsets are fully reset

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- test/rest_request_template/travis_correct_schema_evolution_drop_table.json
- test/rest_request_template/travis_correct_schema_evolution_multi_topic_drop_table.json
- test/test_suit/test_confluent_protobuf_protobuf.py
SNOW-1061855
Fix e2e tests for schema migration with non-buffered channel as underlying transport. The functionality is in main, this PR enables the tests and sets the channel backwards compatible with buffered channel.
> SNOW-1061855 Fix the E2E test for SchemaEvolutionDropTable with a single buffer

- src/main/java/com/snowflake/kafka/connector/internal/streaming/BufferedTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
NOSNOW
Change the verbosity (of first log message occurrence) and message content to improve troubleshooting expience as requested by support team.
> NOSNOW: improve troubleshooting experience for scenario with skipped offsets

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/BufferedTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
In the recent issue (https://github.com/snowflakedb/snowflake-kafka-connector/issues/878) I discovered that sadly we do not have any logs that can be used to track schematization settings and code execution. The reason for this PR is to close this gap.
The logs can be added at INFO level because they appear only at connector startup and when schema change is detected.
> Adding logs to track schematization

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
During performance tests I noticed huge amount of logs (15 times bigger than double buffer) being generated by this DEBUG level statement. We cannot afford it.
> Remove insertRows DEBUG log (called once per row)

- .github/workflows/End2EndTestApache.yml
- .github/workflows/End2EndTestConfluent.yml
- .github/workflows/IntegrationTest.yml
- .github/workflows/StressTest.yml
- test/test_suit/test_confluent_protobuf_protobuf.py
- test/test_suites.py
SNOW-947731
According to https://snowflakecomputing.atlassian.net/browse/SNOW-947731 avro-python3 has bug that causes `TestSchemaEvolutionAvroSR` to fail. After the upgrade the test is failing with another error, but we can merge what I have done so far. 
Btw I discovered why we are limited to Protobuf 3.x.x in tests: https://docs.confluent.io/platform/current/schema-registry/fundamentals/serdes-develop/serdes-protobuf.html#limitations-and-developer-notes
> SNOW-947731 Remove deprecated avro-python3 package

- src/main/java/com/snowflake/kafka/connector/internal/streaming/BufferedTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
SNOW-1514185
Addressing [this comment](https://github.com/snowflakedb/snowflake-kafka-connector/pull/875#discussion_r1720483337) and assigning a reopened channel even when no offset is present in Snowflake.
> SNOW-1514185 Assign new channel when no offset is present in Snowflake

- .github/dependabot.yaml
NO-SNOW Ignore major updates on Kafka dependencies
Dependabot gets confused with Confluent Kafka versioning and wants to update to community edition like [here](https://github.com/snowflakedb/snowflake-kafka-connector/pull/902/files). Preventing major updates should stop this behavior because ce / cs updates are not present in 3.x.x ([source](https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients?repo=confluent-packages))
> NO-SNOW Ignore major updates on Kafka dependencies

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTaskAuthorizationExceptionTracker.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskAuthorizationExceptionTrackerTest.java
SNOW-1623269
Details of this error can be found in JIRA and comments left in the code. The fix is not very complicated but decided to hide it behind a parameter for safety reasons.
I tested this change end-to-end on sfctest0 cause it's tricky to test it automatically.
> SNOW-1623269 Fail sink task on authorization exception from Snowflake

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/Utils.java
> NO-SNOW Release 2.4.1

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/config/CommaSeparatedKeyValueValidator.java
- src/main/java/com/snowflake/kafka/connector/config/ConnectorConfigDefinition.java
- src/main/java/com/snowflake/kafka/connector/config/KafkaProviderValidator.java
- src/main/java/com/snowflake/kafka/connector/config/TopicToTableValidator.java
- src/main/java/com/snowflake/kafka/connector/internal/BufferThreshold.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/IngestionMethodConfig.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/channel/TopicPartitionChannel.java
SNOW-1658905 Initial config refactor
`SnowflakeSinkConnectorConfig` class has a lot of responsibilities:
- holding config keys and default values
- applying default parameters values to the given config
- storing config validators
- serving config definition in a format required by KC framework
This PR extracts some parts of this class to dedicated files. There are still many other things to be fixed around config but this is a 1 hour of work that gives some effect.
> SNOW-1658905 Limit SnowflakeSinkConnectorConfig responsibilities

- src/main/java/com/snowflake/kafka/connector/config/ConnectorConfigDefinition.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergTableSchemaValidator.java
- src/test/java/com/snowflake/kafka/connector/internal/TestSnowflakeConnection.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/BaseIcebergIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergTableSchemaValidatorIT.java
SNOW-1658905
While the `IcebergTableSchemaValidator` is WIP the test setup and base test class will be useful for @sfc-gh-wtrefon to work in parallel on Iceberg.
Note - this PR has zero effect on the production code as.
> SNOW-1658905 Integration tests setup for Iceberg

- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionIT.java
> NO-SNOW: Insert row into iceberg table test

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/config/ConnectorConfigDefinition.java
- src/main/java/com/snowflake/kafka/connector/config/TopicToTableModeExtractor.java
- src/main/java/com/snowflake/kafka/connector/internal/FileNameUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/StageFilesProcessor.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorTest.java
- src/test/java/com/snowflake/kafka/connector/SinkTaskProxyIT.java
- src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java
- src/test/java/com/snowflake/kafka/connector/internal/FileNameTestUtils.java
- src/test/java/com/snowflake/kafka/connector/internal/FileNameUtilsTest.java
- src/test/java/com/snowflake/kafka/connector/internal/IngestionServiceIT.java
- src/test/java/com/snowflake/kafka/connector/internal/SinkServiceIT.java
- src/test/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeStatusMetricsIT.java
- src/test/java/com/snowflake/kafka/connector/internal/StageFilesProcessorTest.java
- src/test/java/com/snowflake/kafka/connector/internal/StageFilesProcessor_FileCategorizerTest.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
SNOW-1642799
Based on the logs analysis - when failed file is handled, it should happen that file is moved to table stage. However, it may happen that the file was removed by external process (i.e. manually) - in such case - exception would interrupt file cleaner process, which in turn - could potentially delete freshly uploaded files upon trying to resume normal operation. 
This PR does 2 things:
- in case of error when moving file to table stage - the cleaning process is not interrupted - file could be removed manually, so we just log the error and continue operation. Worst case scenario - the file would be moved in subsequent cleanup cycles - it may occupy stage for some time. 
- in case of forced restart, the cleaner will not delete "fresh" files - if cleaner process is restarting, …
> SNOW-1642799: added exception handler when moving invalid file to table stage; file cleaner will preserve 'dirty' files a bit longer

- src/main/java/com/snowflake/kafka/connector/config/IcebergConfigValidator.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergDDLTypes.java
- src/main/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergInitService.java
- src/main/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergTableSchemaValidator.java
- src/test/java/com/snowflake/kafka/connector/config/IcebergConfigValidationTest.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/BaseIcebergIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergInitServiceIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergInitServiceTest.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergTableSchemaValidatorIT.java
> SNOW-1680410 adjust validations and create metadata column if not exists

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DefaultStreamingConfigValidator.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorLogsTest.java
SNOW-1686497
When single buffering is enabled the `buffer.size.bytes` parameter is still passed to the ingest-sdk. Marking it as deprecated was misleading.
> SNOW-1686497 Remove single buffer warning for "buffer.size.bytes"

- test/test_suites.py
- test/test_verify.py
SNOW-1728000
The clean flag in e2e tests is always set to true so it can be deleted.
> SNOW-1728000 Remove clean flag from tests

- test/test_executor.py
- test/test_selector.py
- test/test_verify.py
SNOW-1728000
`test_verify.py` was so complicated that adding any new logic there seemed impossible to me. I decided to introduce the following abstractions:
- TestSelector - which one and only role is to filter tests according to given parameters
- TestExecutor - which one and only role is to run tests
Overall there is still huge space for improvement but this refactor makes cloud vendor specific filtering much easier.
> SNOW-1728000 TestExecutor and TestSelector for e2e tests

- .github/workflows/StressTest.yml
> PROD-135021 Reduced stress tests matrix

- test/test_selector.py
- test/test_suites.py
- test/test_verify.py
SNOW-1728000
This PR contains:
- Adding cloud_platform flag to e2e test suites objects
- Complete tests filtering (based on the user input, apache/confluent and cloud platform)
- Some minor renaming from camel case to snake case (to be more Python-ish)
- Code formatter ([black](https://github.com/psf/black) with default settings) for test_suites.py and test_selector.py
> SNOW-1728000 Cloud platform tests filtering

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientPropertiesTest.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergInitServiceIT.java
This reverts commit f0e5f230ff710e809671f5f0a27b23302c8cb3ba.
We decided to not enable this setting by default in 2.5.0 release because we are not sure what is the impact on the first read performance.
> Revert "NO-SNOW Enable single buffering in Snowpipe Streaming by default (#924)"

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/Utils.java
> NO-SNOW Release 2.5.0

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectStreamingClientHandler.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProperties.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionIT.java
related to SNOW-1728002
It's temporary approach. Finally we will set iceberg mode by invoking SnowflakeStreamingIngestClientFactory.builder.setIceberg(true) but the method is not yet public.
> SNOW-1728002 get rid of reflection when enabling iceberg streaming

- pom.xml
- pom_confluent.xml
- scripts/process_licenses.py
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/ApacheIcebergColumnSchema.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergColumnTree.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergColumnTypeMapper.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergDataTypeParser.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergFieldNode.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergTableSchema.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionSchemaEvolutionIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/schemaevolution/iceberg/ParseIcebergColumnTreeTest.java
SNOW-1665420
The goal of this PR is to implement logic to parse plain iceberg schema. That schema will be retrieved from a channel during schema evolution. 
I generate IcebergColumnTree from Iceberg schema. 
I added logic to generate **part** of the query that will be used to alter the column. Generating query is out of scope but It's the best way to test the logic. I didn't handle nullability of the columns yet.
> SNOW-1665420 add logic to parse Iceberg schema

- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/sql/ComplexJsonRecord.java
SNOW-1761519
This bug was discovered at the beginning of work with Iceberg ingestion. I validated locally with the most recent ingest sdk that it passes.
The test will be enabled after ingest sdk 3.0.1 release.
> SNOW-1761519 Fix empty arrays in Iceberg ingestion

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/config/IcebergConfigValidator.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorTest.java
- src/test/java/com/snowflake/kafka/connector/config/IcebergConfigValidationTest.java
- src/test/java/com/snowflake/kafka/connector/config/SnowflakeSinkConnectorConfigBuilder.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientPropertiesTest.java
- test/rest_request_template/travis_correct_schema_evolution_multi_topic_drop_table.json
- test/test_suit/test_schema_evolution_multi_topic_drop_table.py
SNOW-1805174
This PR contains:
- enabling single buffer by default + fixes for some tests
- validation that blocks running iceberg ingestion with double buffer
> SNOW-1805174 Enable single buffer by default

- .github/workflows/End2EndTestApache.yml
- .github/workflows/End2EndTestConfluent.yml
- .github/workflows/IntegrationTest.yml
- .github/workflows/StressTest.yml
NO-SNOW
CI recently started to fail because of some ubuntu packages disappearance.
> NO-SNOW Fix missing ubuntu packages error in CI

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- test/rest_request_template/iceberg_avro_aws.json
- test/rest_request_template/iceberg_json_aws.json
- test/rest_request_template/iceberg_schema_evolution_avro_aws.json
- test/rest_request_template/iceberg_schema_evolution_json_aws.json
- test/test_suit/base_iceberg_test.py
- test/test_suit/iceberg_avro_aws.py
- test/test_suit/iceberg_json_aws.py
- test/test_suit/iceberg_schema_evolution_avro_aws.py
- test/test_suit/iceberg_schema_evolution_json_aws.py
- test/test_verify.py
SNOW-1831140
A solid contribution to iceberg JSON e2e's + some minor bugs fixes.
> SNOW-1831140 E2e tests of Iceberg JSON ingestion

- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergTableSchemaResolver.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionNoSchemaEvolutionIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionSchemaEvolutionIT.java
- test/test_suites.py
> SNOW-1820302 Integrate with ingest sdk 3.0.1

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergColumnTreeFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergColumnTypeMapper.java
- src/test/java/com/snowflake/kafka/connector/dlq/InMemoryKafkaRecordErrorReporter.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergColumnTypeMapperTest.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/ParseIcebergColumnTreeTest.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionNoSchemaEvolutionIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionSchemaEvolutionIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/sql/ComplexJsonRecord.java
- test/test_suit/base_iceberg_test.py
- test/test_suit/iceberg_schema_evolution_json_aws.py
> SNOW-1731255: Put null or empty json nodes to DLQ for schema evolution

- src/main/java/com/snowflake/kafka/connector/internal/FileNameUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/KCLogger.java
- src/main/java/com/snowflake/kafka/connector/internal/OffsetContinuityRanges.java
- src/main/java/com/snowflake/kafka/connector/internal/OffsetScanResult.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/test/java/com/snowflake/kafka/connector/internal/FileNameUtilsTest.java
Refactored from:
https://github.com/snowflakedb/snowflake-kafka-connector/pull/1023
> NO-SNOW Improve offset logging for Snowpipe

- src/main/java/com/snowflake/kafka/connector/internal/streaming/BufferedTopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
This is a copy of https://github.com/snowflakedb/snowflake-kafka-connector/pull/1037
Please refer to the original PR for detailed description.
> Fix IndexOutOfBoundException thrown when offsets are not continous during schema-evolution

- src/main/java/com/snowflake/kafka/connector/DefaultConnectorConfigValidator.java
- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorTest.java
- src/test/java/com/snowflake/kafka/connector/internal/SinkServiceIT.java
This is the exact copy of https://github.com/snowflakedb/snowflake-kafka-connector/pull/1041
> [CONFLUENT] Add configuration to disable reprocess files cleanup by v1Cleaner

- test/test_data/protobuf/pom.xml
This subproject is only for test data generation, but some vulnerabilities scanners raise alerts regarding it.
> CASEC-9813 Bump protobuf in test-data to 3.25.5

- pom.xml
- pom_confluent.xml
- test/run_test_apache.sh
[SNOW-1899609]
[SNOW-1899609]: https://snowflakecomputing.atlassian.net/browse/SNOW-1899609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SNOW-1899609 Bump bpckix-fips

- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/BufferedTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/ChannelOffsetTokenMigrator.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java
SNOW-1933073
Offset token migration is called for every channel at startup. Even a single failure results in a fatal error that cause connector restart which then cause another batch of requests to be called. Massive number of offset migration requests has recently caused problems on the GS side.
Thanks to the retry policy we can retry just one request that failed which is better for both backend and connector.
> SNOW-1933073 Add retry policy for channel migration

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DefaultStreamingConfigValidator.java
Marking parameter as deprecated before future removal.
> CONN-10462 Double buffering deprecation

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/DelayedSchemaEvolutionService.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingSinkServiceBuilder.java
SNOW-2034182
When schematization is enabled it is possible for the connector to lose a single message that triggers changing a table schema due to a race condition. Assuming that `offset=n` triggers the schema evolution:
1. `this.channel.insertRow(transformedRecord, Long.toString(offset))` is called for offset=n-1 (no schema evolution)
2. `this.channel.insertRow(transformedRecord, Long.toString(offset))` is called for offset=n
3. [Race condition] The background ingest sdk flush thread sends and commits the data with offsets up to n (inclusive) into Snowflake. Record n is considered as error and is skipped due to `OnErrorOption.CONTINUE` client setting.
4. The channel is invalidated and reopened. Connector reports offset n+1 as the next starting point for Kafka Connect
Note that data won't …
> SNOW-2034182 [Data loss fix] Change OnErrorOption from CONTINUE to SKIP_BATCH

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceFactory.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java
- src/test/java/com/snowflake/kafka/connector/internal/SinkServiceIT.java
- src/test/java/com/snowflake/kafka/connector/internal/TombstoneRecordIngestionIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2AvroSchematizationIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2StopIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingSinkServiceBuilder.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionIT.java
CONN-10472
This is the last part of the refactoring effort started after double buffer removal 💪 Intentions behind this PR:
- Creation of `SnowflakeSinkServiceV1` and `SnowflakeSinkServiceV2` is completely separated
- `SnowflakeSinkServiceV2` has a single constructor and all final fields
- `SnowflakeSinkService` interface no longer contains buffer related methods as they are Snowpipe specific
- `SnowflakeSinkServiceFactory` is used only to construct instances of `SnowflakeSinkServiceV1`
> CONN-10472 Separate SnowflakeSinkServiceV1 and SnowflakeSinkServiceV2 creation

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/channel/ExposingInternalsTopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
CONN-10463
Another small refactor discovered while creating a PoC:
- `SnowflakeStreamingIngestChannel getChannel();` is moved to the `DirectTopicPartitionChannel` class. This is crucial because a new implementation of the channel will not use a v1 channel at all.
- `boolean isPartitionBufferEmpty();` is simply deleted after double buffer removal
- `SnowflakeTelemetryService getTelemetryServiceV2();` - is also deleted because its only usage doesn't bring any value
> CONN-10463 ExposingInternalsTopicPartitionChannel refactor

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingRecordService.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
CONN-10476
During the SSv2 PoC implementation I discovered that a significant part of `DirectTopicPartitionChannel` code will be used in SSv2 as well. This PR makes the code available to be reused with the composition.
> CONN-10476 Extract common part of SSv1 and SSv2

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/LatestCommitedOffsetTokenExecutor.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/channel/TopicPartitionChannel.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
Failsafe logic is shared across Snowpipe Streaming v1 and v2 so it's worth extracting to a separate class.
> CONN-10486 Failsafe logic separation

- .github/workflows/End2EndTestApache.yml
- .github/workflows/End2EndTestConfluent.yml
- .github/workflows/IntegrationTest.yml
- .github/workflows/StressTest.yml
- pom.xml
- pom_confluent.xml
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorTest.java
Migration to JDK 11 including removal of JDK 8 testing.
The main reasons for the migration are:
- enable support for Snowpipe Streaming v2
- long-lasting deprecation and upcoming removal of JDK 8 from Kafka / Kafka Connect environment
> CONN-10478 Java 11 migration

- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2BaseIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2LegacyIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2OAuthIT.java
- src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2SchematizationIT.java
In order to ensure that SSv2 works I would like to test the same ITs as we have for SSv1. This PR fixes a couple of problems with the existing ITs:
- All tests were run twice for password and oAuth authentication. This is fundamentally wrong because authentication method doesn't change anything in the service logic. I extracted a single oAuth test and left rest of them as password based.
- Configuration validation tests were inappropiate for IT level testing so I decided to delete it. It's just to heavy.
- Some of the tests were strongly connected with double buffering logic that was removed recently
- Schematization tests were moved to a a separate file
Of course it is faaar from being perfect but it is good enough to continue development of SSv2.
> CONN-10486 SnowflakeSinkServiceV2IT refactor

- src/main/java/com/snowflake/kafka/connector/records/IcebergTableStreamingRecordMapper.java
- src/main/java/com/snowflake/kafka/connector/records/SnowflakeTableStreamingRecordMapper.java
- src/main/java/com/snowflake/kafka/connector/records/StreamingRecordMapper.java
- src/test/java/com/snowflake/kafka/connector/records/IcebergTableStreamingRecordMapperTest.java
- src/test/java/com/snowflake/kafka/connector/records/SnowflakeTableStreamingRecordMapperTest.java
- src/test/java/com/snowflake/kafka/connector/records/StreamingRecordMapperTest.java
CONN-10496 Record data mapping for SSv2
In SSv1 Objects and Arrays were converted into Strings containing JSON.
In SSv2 it would be problematic because it would require placing additional logic within the pipe e.g. `PARSE_JSON($1) AS RECORD_CONTENT`. To keep pipe simple and avoid its recreation when schema change the data is mapped into `Map<String, Object>`.
> CONN-10496 Record data mapping for SSv2

- .github/workflows/GoogleJavaFormat.yml
- pom.xml
- pom_confluent.xml
- src/main/java/com/snowflake/kafka/connector/Utils.java
FLOW-4165
Bumping Confluent packages to 7.9.2 in order to fix vulnerability.
This commit marks 3.2.2 release.
> FLOW-4165 Bump confluent packages to 7.9.2 / Release 3.2.2

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/Utils.java
- src/main/java/com/snowflake/kafka/connector/config/ConnectorConfigDefinition.java
- src/main/java/com/snowflake/kafka/connector/config/IcebergConfigValidator.java
- src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/DefaultStreamingConfigValidator.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/validation/JWTManagerProvider.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/validation/RowsetApiRowSchemaProvider.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorTest.java
- src/test/java/com/snowflake/kafka/connector/config/IcebergConfigValidationTest.java
- src/test/java/com/snowflake/kafka/connector/config/SnowflakeSinkConnectorConfigBuilder.java
- test/apache_properties/server.properties
- test/connect-log4j.properties
- test/test_verify.py
To make review of the main SSv2 PR easier I extracted the part related to the parameter management:
- Adding parameter `snowflake.streaming.v2.enabled`
- Iceberg not supported in SSv2 validation
- SSv2 in PuPr supports only the default role - `snowflake.role.name` cannot be provided in SSv2
- a couple of one-liners
> CONN-10463 SSv2 config and mini-refactors

- pom.xml
- pom_confluent.xml
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionSchemaEvolutionIT.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergInitServiceIT.java
1. `kafka-schema-rules` dependency was added during update of Confluent packages to 7.6.0 as a result of e2e test failure. With the current version it is no longer needed which is very convenient in terms of vulnerability present in the transitive dependency.
2. Iceberg tests needs adjustment after latest Snowflake BCR that changed the size of VARCHAR columns.
> SNOW-2184975 Remove kafka-schema-rules dependency / fix Iceberg tests

- src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/DefaultStreamingConfigValidator.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/InsertErrorMapper.java
- src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergTableSchemaResolver.java
- src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryService.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorTest.java
- src/test/java/com/snowflake/kafka/connector/config/IcebergConfigValidationTest.java
- src/test/java/com/snowflake/kafka/connector/internal/OAuthURLTest.java
- src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
- src/test/java/com/snowflake/kafka/connector/internal/TombstoneRecordIngestionIT.java
- src/test/java/com/snowflake/kafka/connector/records/AbstractMetaColumnTest.java
- src/test/java/com/snowflake/kafka/connector/records/IcebergTableStreamingRecordMapperTest.java
- src/test/java/com/snowflake/kafka/connector/streaming/iceberg/sql/ComplexJsonRecord.java
- src/test/java/net/snowflake/ingest/streaming/FakeSnowflakeStreamingIngestChannel.java
This combo PR contains 3 changes:
1. Revert of role validation for SSv2. Testing on MSK showed that connector throws NPE in `boolean hasSchemaEvolutionPermission(String tableName, String role);`. Service ITs missed that one, because config validations are called on a different level.
2. Adding usage of SSv2 and Iceberg to telemetry.
3. Change guava Immutable collection to Java 11 collections
> CONN-10463 Revert role validation + telemetry improvements + Java 11 fixes

- pom.xml
- pom_confluent.xml
SNOW-2197881 OSSRH migration
On June 30 OSSRH, which was the method we used to publish artifacts into maven, was shut down  https://central.sonatype.org/pages/ossrh-eol/
The simplest migration path is to use ossrh staging api: https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/
> SNOW-2197881 OSSRH migration

- pom.xml
- pom_confluent.xml
Cherry-picking from `3.2.x` to master: https://github.com/snowflakedb/snowflake-kafka-connector/pull/1139
With `3.2.3` finally released we know that it works!
> SNOW-2197881 Change OSSRH link for nexus-staging-maven-plugin

- src/main/java/com/snowflake/kafka/connector/internal/streaming/DefaultStreamingConfigValidator.java
- src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorTest.java
…
CONN-10559 Do not allow schematization config option when using SF Streaming SSv2
> CONN-10559 Do not allow schematization config option when using SF Streaming SSv2
