.gitignore
pom.xml

Upgrade log4j lib

---

pom.xml
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryServiceV1.java
src/test/java/com/snowflake/kafka/connector/internal/SinkServiceIT.java

upgrade JDBC

---

src/main/java/com/snowflake/kafka/connector/internal/FileNameUtils.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
src/test/java/com/snowflake/kafka/connector/internal/FileNameUtilsTest.java

Separate PREFIX and FILE NAME when uploading data to support GCP

---

pom.xml

SNOW-144364

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java

qprecommit called before sink task is initialized

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java

SNOW-144248 fix precommit bug

---

test/build_image.sh
test/helm_values/snow_values_5.4.yaml
test/rest_request_template/travis_correct_avro_avro.json
test/rest_request_template/travis_correct_avrosr_avrosr.json
test/rest_request_template/travis_correct_json_json.json
test/rest_request_template/travis_correct_string_avro.json
test/rest_request_template/travis_correct_string_avrosr.json
test/rest_request_template/travis_correct_string_json.json
test/run_test.sh
test/setup_k8s.sh
test/test_suit/__init__.py
test/test_suit/test_avro_avro.py
test/test_suit/test_avrosr_avrosr.py
test/test_suit/test_json_json.py
test/test_suit/test_string_avro.py
test/test_suit/test_string_avrosr.py
test/test_suit/test_string_json.py
test/test_suit/test_utils.py
test/test_verify.py

Added name salt
Delete pipes, tables and stages after test is done
Restructured code for better scalability

SNOW-142849 added name salt and restructured test code

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java
src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
src/main/java/com/snowflake/kafka/connector/Utils.java
src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
src/test/java/com/snowflake/kafka/connector/ConnectorTest.java
src/test/java/com/snowflake/kafka/connector/SecurityTest.java
test/helm_values/snow_values_5.0.yaml
test/helm_values/snow_values_5.4.yaml
test/helm_values/snow_values_5.5.yaml
test/rest_request_template/travis_correct_json_json.json

Major changes:
- removed configuration related with schema registry, as it is not necessary
- added new versions in helm values
- added single field config validation

SNOW-152647 Single field config validation

---

.github/workflows/End2EndFullTest.yml
src/test/java/com/snowflake/kafka/connector/internal/SinkServiceIT.java
test/apache_properties/connect-distributed.properties
test/apache_properties/server.properties
test/apache_properties/zookeeper.properties
test/build_apache.sh
test/build_image.sh
test/run_test_apache.sh

Every PR will be tested on Confluent 5.5.0 and Apache 2.5.0
Added a full version test that will run every night at 1am PT, it will test on Confluent 5.0.0, 5.2.0, 5.4.0, 5.5.0 and Apache 2.0.0, 2.2.0, 2.4.0, 2.5.0.

SNOW-99267 Added test to Apache

---

test/test_suit/test_avro_avro.py
test/test_suit/test_avrosr_avrosr.py
test/test_suit/test_json_json.py
test/test_suit/test_native_string_avrosr.py
test/test_suit/test_native_string_json_without_schema.py
test/test_suit/test_string_avro.py
test/test_suit/test_string_avrosr.py
test/test_suit/test_string_json.py
test/test_suit/test_utils.py
test/test_verify.py

We validate content of row 1 of each table in end 2 end test.

SNOW-159803 Validate table content in end2end test

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java

Batch delete on stage, which will increase the performance of our cleaner.

Batch delete in cleaner and fixed a potential SQL ingestion bug

---

src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java

Updated error code for table/stage/pipe creation failure

Error message update for confluent cloud validation

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java
src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceFactory.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryServiceV1.java
src/test/java/com/snowflake/kafka/connector/ConnectorTest.java

Changes:
- SNOW-161134 backoff when important http call is throttled
- SNOW-161149 batch call Snowpipe in recovery
- SNOW-161148 backoff telemetry

SNOW-161134 Batch Snowpipe in recovery and backoff when important http call is throttled 

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceFactory.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java

changed some error log to warnings

SNOW-163246 Minor change to remove hard coded ingestion service port

---

.github/workflows/End2EndTest.yml
test/run_test.sh
test/run_test_apache.sh
test/run_test_confluent.sh
test/utils.sh

Moved common part of three scripts to a function
Added a function to dump thread every 5 seconds to track thread leak issue

SNOW-155010 Added test for thread leak

---

.github/workflows/End2EndTest.yml
src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
src/test/java/com/snowflake/kafka/connector/internal/SnowflakeURLTest.java
test/run_test_confluent.sh
test/test_verify.py

- removed pressure test
- changed logging to standard one to make it compatible with java 11.
- removed useless deletion on testing
- added a test to test private link on snowflakeURL

Minor fixes of testing and dependency

---

test/run_test_apache.sh
test/run_test_confluent.sh
test/test_data/protobuf/pom.xml
test/utils.sh

Test protobuf on Apache Kafka as well.

SNOW-177025 Added protobuf test for Apache Kafka

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
test/rest_request_template/travis_pressure_restart.json
test/run_test_apache.sh
test/run_test_confluent.sh
test/test_suit/test_avro_avro.py
test/test_suit/test_avrosr_avrosr.py
test/test_suit/test_json_json.py
test/test_suit/test_native_complex_smt.py
test/test_suit/test_native_string_avrosr.py
test/test_suit/test_native_string_json_without_schema.py
test/test_suit/test_native_string_protobuf.py
test/test_suit/test_pressure_restart.py
test/test_suit/test_string_avro.py
test/test_suit/test_string_avrosr.py
test/test_suit/test_string_json.py
test/test_verify.py
test/utils.sh

The most important modification is in **SnowflakeSinkTask.java stop() and preCommit()**.
stop():
- do nothing now
preCommit():
- when there is error, return empty map to indicate that offset commitment is not desired
Customer reported that when updating the connector's configuration, there is data loss. Modifications on the e2e test:
- Added a test that will update the connector's configuration every minute (this test reproduced the customer's bug). 
- Moved connector creation from shell script to python
- Added another round of testing to allow not only parallel testing, but also serial testing

SNOW-178013 Fix data losing issue

---

.github/workflows/End2EndFullTest.yml
.github/workflows/End2EndFullTestAzure.yml
.github/workflows/End2EndTest.yml
.github/workflows/End2EndTestAzure.yml

**Only Github Action config file updates. NO test/code changes.**
Using matrix in Github Action caused the build process `mvn verify` to throw:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (default) on project snowflake-kafka-connector: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:3.3.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-assembly-plugin:jar:3.3.0 -> org.apache.maven:maven-plugin-api:jar:3.0: Failed to read artifact descriptor for org.apache.maven:maven-plugin-api:jar:3.0: Could not transfer artifact org.apache.maven:maven-plugin-api:pom:3.0 from/to central …
```

SNOW-200255 Fix AWS/Azure test

---

.github/workflows/End2EndFullTest.yml
.github/workflows/End2EndFullTestAzure.yml
.github/workflows/End2EndTest.yml
.github/workflows/End2EndTestAzure.yml
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryServiceV1.java
src/test/java/com/snowflake/kafka/connector/internal/MetaColumnIT.java
test/build_apache.sh
test/run_test_apache.sh
test/run_test_confluent.sh
test/test_suit/test_string_json.py
test/test_verify.py

Invalidate m2 cache in all test. 
The connector behaves different on Kafka version <= 2.2.0 on header parsing. So need to modify the test verification.

SNOW-200255 Fix Test

---

pom.xml
pom_confluent.xml
src/test/java/com/snowflake/kafka/connector/mock/MockSchemaRegistryClient.java

Bump up dependency version of the converter. Implemented new APIs in the mock client.

SNOW-201517 Fixed converter class loader error by upgrading versions

---

README-TEST.md

Link to the preview of this file: https://github.com/snowflakedb/snowflake-kafka-connector/blob/2232549d16b551995213beafa97be1dd75e60025/README-TEST.md

SNOW-213581 Added test documentation

---

src/test/java/com/snowflake/kafka/connector/internal/IngestionServiceIT.java

Fixed flaky test exposed in this Github Action: https://github.com/snowflakedb/snowflake-kafka-connector/pull/247/checks?check_run_id=1312016101

SNOW-213552 Fix flaky test on ingestion

---

src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java

Add test for AvroConverter to increase coverage. Tested a parameter break.on.schema.registry.error.

SNOW-213559 Add test for AvroConverter to increase coverage

---

src/main/java/com/snowflake/kafka/connector/records/SnowflakeRecordContent.java
src/test/java/com/snowflake/kafka/connector/ConnectorIT.java
src/test/java/com/snowflake/kafka/connector/SinkTaskIT.java
src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java

Added test that covers the top level object SnowflakeSinkTask and SnowflakeSinkConnector

SNOW-197027 Add test that covers SnowflakeSinkTask and SnowflakeSinkConnector

---

.github/workflows/StressTest.yml
README-TEST.md
test/test_suit/test_pressure.py
test/test_verify.py

Add stress test as weekly test. Updated test document. Updated version can be previewed here: https://github.com/snowflakedb/snowflake-kafka-connector/blob/55f8f684af175d2182c4ae2cfc45f7b4b73b91ef/README-TEST.md

SNOW-215402 Added stress test

---

test/test_suit/test_pressure_restart.py
test/test_verify.py

Modified restart test to test more Kafka Connect APIs.

SNOW-212310 Added test for more Kafka Connect APIs

---

src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java
src/test/java/com/snowflake/kafka/connector/records/RecordContentTest.java

Added test for null inputs for convertToJson api.
Added test of broken input record in AVRO converter, where the parsing AVRO step fails.

Improve coverage

---

pom.xml

https://repo.maven.apache.org/maven2/net/snowflake/snowflake-ingest-sdk/
builds fine:
`./build_apache.sh ../../snowflake-kafka-connector package`

Bumping snowpipe SDK version

---

pom_confluent.xml

- We probably need to run a our tests in `pom_confluent.xml`

Modify dependency in confluent pom

---

test/test_verify.py

Increase the retry count for retry-able errors.

Reset retry count to 120

---

src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeInternalOperations.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeInternalStage.java
src/test/resources/log4j.properties
test/connect-log4j.properties
test/run_test_apache.sh
test/run_test_confluent.sh

Add test which simulates this. 
https://www.confluent.io/blog/kafka-connect-improvements-in-apache-kafka-2-3/
Clients should do this on their end. But give sample and improve documentation. 
We will also add this in documentation: 
Tested locally.

Example connect-log4j.properties for testing

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/records/RecordService.java
src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java
test/test_suit/test_string_json_proxy.py

For running automated Tests 
#282 
CC: @C0urante

Fix handling of schemaless Date objects

---

src/main/java/com/snowflake/kafka/connector/records/RecordService.java
src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java

Add thread safety around simple data format

---

src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java

No Functional Change
https://snowflakecomputing.atlassian.net/browse/SNOW-219520

Add comments to cleaner code for better readability

---

src/test/java/com/snowflake/kafka/connector/internal/SinkServiceIT.java

SNOW-298877
Adding a test to repro behavior of tombstone records. 
Tombstone records are those records whose key is non null but value(Payload) is null. 
- We have decided that we would do a breaking change and **not** put an empty JSON(`{}`) inside table. 
- We can use SMT to filter empty records. 
- https://kafka.apache.org/documentation/#connect_transforms

Added test to verify behavior of tombstone records

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
src/main/java/com/snowflake/kafka/connector/Utils.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceFactory.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryBasicInfo.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeCreation.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeStatus.java
src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
src/test/java/com/snowflake/kafka/connector/internal/SnowflakeTelemetryPipeStatusMetricsIT.java
src/test/java/com/snowflake/kafka/connector/internal/TelemetryUnitTest.java

- Default is true
- False would not emit custom metrics to JMX

Add JMX option for custom metrics

---

src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
src/main/java/com/snowflake/kafka/connector/records/SnowflakeAvroConverter.java
src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java

Opening a PR here so that we can run tests. 
Re: #312

Avro converter supports a fixed reader schema 

---

pom.xml
pom_confluent.xml
src/test/java/com/snowflake/kafka/connector/ConnectorIT.java
src/test/java/com/snowflake/kafka/connector/SinkTaskProxyIT.java
src/test/java/com/snowflake/kafka/connector/internal/InternalStageIT.java
src/test/java/com/snowflake/kafka/connector/internal/ResetProxyConfigExec.java
src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java

Upgrade jdbc to latest version

---

pom.xml
pom_confluent.xml

We will have to wait for 3.13.13 to be released to maven repo before we can rerun and push to master.

Bump up jdbc to 3.13.13

---

src/main/java/com/snowflake/kafka/connector/records/SnowflakeAvroConverter.java
src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java

Clone of https://github.com/snowflakedb/snowflake-kafka-connector/pull/356
Opening this since we need to run Github action tests and it somehow doesnt run from external PR.

Pr 356 anekdoti

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

Notes:
- New config for delivery guarantee
- delivery.guarantee = AT_LEAST_ONCE/EXACTLY_ONCE
- default - AT_LEAST_ONCE
- EXACTLY_ONCE - Preview feature

Release version 1.7.0

---

pom.xml
test/build_apache.sh

We will replace it with beta version of ingest SDK once it is released. 
So this is just a placeholder PR. 
PS:
- Also update `pom_confluent.xml`
- Also note base branch, it is kept as `japatel-279791-master-streaming-snowpipe-prpr` instead of master

Added built jar from private ingest sdk

---

pom.xml
src/main/java/com/snowflake/kafka/connector/internal/PartitionBuffer.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
src/main/java/com/snowflake/kafka/connector/records/RecordService.java
src/test/java/com/snowflake/kafka/connector/records/HeaderTest.java
src/test/java/com/snowflake/kafka/connector/records/MetaColumnTest.java
src/test/java/com/snowflake/kafka/connector/records/ProcessRecordTest.java
src/test/java/com/snowflake/kafka/connector/records/RecordContentTest.java
test/build_apache.sh

- Just a Refactoring PR benefitted for StreamingIngest Based implementations.
- Also added some javadocs for more readability.
- No functional change.

Refactor SinkServiceV1, PartitionBuffer and RecordService

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

Will push this to master. 
- JDBC version 3.13.14
- jackson-core and jackson-databind 2.12.6 for resolving FasterXML/jackson-databind#3328 
- Fixes #383

Release branch 1.7.1

---

test/perf_test/pom.xml
test/test_data/protobuf/pom.xml

https://github.com/snowflakedb/snowflake-kafka-connector/pull/392/checks?check_run_id=5057340778

Resolve few vulnerabilities shown on whitesource

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
src/main/java/com/snowflake/kafka/connector/Utils.java
src/main/java/com/snowflake/kafka/connector/internal/PartitionBuffer.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceFactory.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/IngestionMethodConfig.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
src/main/java/com/snowflake/kafka/connector/records/RecordService.java
src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
src/test/java/com/snowflake/kafka/connector/records/HeaderTest.java
src/test/java/com/snowflake/kafka/connector/records/MetaColumnTest.java
src/test/java/com/snowflake/kafka/connector/records/ProcessRecordTest.java
src/test/java/com/snowflake/kafka/connector/records/RecordContentTest.java
test/build_apache.sh
test/rest_request_template/datagen_connector.json
test/rest_request_template/travis_correct_streaming_snowpipe_string_json.json

This is a PR for pushing the already approved changes to master so that subsequent PRs can be opened against master. 
There is no change apart from merging these three together in this PR.
1. https://github.com/snowflakedb/snowflake-kafka-connector/pull/379
2. https://github.com/snowflakedb/snowflake-kafka-connector/pull/381
3. https://github.com/snowflakedb/snowflake-kafka-connector/pull/382
I have reverted one change which was using a built jar, instead we can use beta version of ingest SDK.

SNOW-279791 Basics of streaming snowpipe 

---

src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java

- Renamed few fields and added more javadocs.
- Add test for close channel exception

Refactor fetching offsetToken method to be reusable for multiple calls

---

pom.xml
pom_confluent.xml

Just pom change to trigger whitesource.

Add failsafe as dependency

---

src/main/java/com/snowflake/kafka/connector/internal/PartitionBuffer.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java

- Max int value - 2147483647 = ~1.999 GB
- We are bounded by Heap size but we dont want to be limited by max int value.

SNOW-550868 Change buffer size from integer to long

---

src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingBufferThreshold.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingBufferThresholdTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java

- Refactored buffer threshold logic inside another final class
- Fixed bug where thresholds were not checked on every records insertion
to buffer.

BUG-FIX - Check count and bytes threshold on every insert into to buffer

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
src/main/java/com/snowflake/kafka/connector/Utils.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java

SNOW-550666 deprecate custom(Snowflake) converter for streaming

---

pom.xml
pom_confluent.xml

Use latest version of ingest SDK.

NO-SNOW Use ingest sdk 1.0.1-beta

---

pom.xml

This should fix https://github.com/snowflakedb/snowflake-kafka-connector/issues/411

NO-SNOW: fix security vulnerability

---

src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java

Just more test for Avro, util function will be useful later too!

Add huge avro schema test for buffer bytes threshold

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java
src/test/java/com/snowflake/kafka/connector/ConnectorConfigTest.java
src/test/java/com/snowflake/kafka/connector/UtilsTest.java

Copy of closed PR: https://github.com/snowflakedb/snowflake-kafka-connector/pull/461

Fix for invalid connector name - Issue 456

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java
src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java

Update the ingest SDK to [v1.0.2-beta.3](https://github.com/snowflakedb/snowflake-ingest-java/releases/tag/v1.0.2-beta.3)

Release version 1.8.1

---

deploy.sh

Disable whitesource checks as we migrated to synk

Disable whitesource checks as we migrated to synk

---

pom.xml
pom_confluent.xml

Create release 1.8.2

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java
test/test_suit/test_schema_mapping.py

This will not work unless we releases 1.1.0.
I will wait for it and merge gates to pass, I am just keeping PR ready.

Bump Ingest SDK to 1.1.0 and release 1.9.0

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

Push after https://github.com/snowflakedb/snowflake-kafka-connector/pull/556

NO-SNOW Release 1.9.1 for Snowpipe Streaming

---

README.md

Was having OCD for not showing status on Home page in Readme.  https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

[NO-SNOW] MINOR - Update README.md

---

pom.xml
pom_confluent.xml
test/rest_request_template/snowpipe_streaming_schema_mapping_dlq.json
test/rest_request_template/snowpipe_streaming_string_json_dlq.json
test/test_suit/test_snowpipe_streaming_schema_mapping_dlq.py
test/test_suit/test_snowpipe_streaming_string_json_dlq.py
test/test_verify.py

- Insert bad data in value
- Watch it going into DLQ
- Poll DLQ and verify results. 
Next: Will think of more test cases.

SNOW-760171 Part 1: Test to verify DLQ results 

---

.github/workflows/cla_bot.yml

Add CLA bot, copied file from other repos:
https://github.com/search?q=org%3Asnowflakedb+CLA_BOT_TOKEN&type=code

Add cla bot from snowflake-connector-python repo

---

.gitignore
format.sh

It is currently difficult for external PRs to format the code, so this PR adds a script to download the jar and format
Script from the ingest repo: https://github.com/snowflakedb/snowflake-ingest-java/blob/master/format.sh

Add format script

---

pom.xml
pom_confluent.xml
src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskStreamingTest.java

- Significant improvements over previous versions. https://github.com/snowflakedb/snowflake-ingest-java/releases/tag/v1.1.2 and https://github.com/snowflakedb/snowflake-ingest-java/releases/tag/v1.1.3
- Also has useProxyHost support for snowpipe

[NO-SNOW] Use latest version of Ingest SDK

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

- Upgrades the version to 1.9.2
- Release notes will be available in release tag. 
@test
Performed:
- Load tests. 
- Chaos tests.

NO-SNOW Release version 1.9.2

---

pom_confluent.xml

- Ask from confluent. 
- https://docs.confluent.io/platform/7.3/connect/kafka-connect-maven-plugin/site/kafka-connect-mojo.html

NO-SNOW Kafka connector supports any encoding, not only UTF-8

---

test/rest_request_template/travis_correct_schema_evolution_json.json
test/test_suit/test_schema_evolution_json.py
test/test_suites.py

Miscommunication on this PR [comment](https://github.com/snowflakedb/snowflake-kafka-connector/pull/653#discussion_r1232893748) on what test needed to be removed. Adding e2e test back

Revert removal of TestSchemaEvolutionJson e2e test

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

Upgrades version to 1.9.4. See tag for rel notes
Testing
- Load tests: IP
- Chaos tests: IP

Release version 1.9.4

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java

Title
[Diff](https://github.com/snowflakedb/snowflake-kafka-connector/compare/v1.9.4...rcheng-rel2.0.0) with last release (v1.9.4). Literally just sdk and version upgrades
Will not be taking the JMX changes - which is just this pr: https://github.com/snowflakedb/snowflake-kafka-connector/pull/672
Will be taking this revert - https://github.com/snowflakedb/snowflake-kafka-connector/pull/678

Create release v2.0.0 for GA

---

src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java

Title. See this [issue](https://github.com/snowflakedb/snowflake-kafka-connector/issues/441)

Change pipe already registered log from error to warn level

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

Note v2.0.1 will not contain oauth changes

Release v2.0.1

---

src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProvider.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProviderTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java

No need to explicitly ask users to pass in one client optimization config

SNOW-903979 Set default to true for one client optimization

---

pom.xml
pom_confluent.xml

Ingest SDK 2.0.2 -> 2.0.3
Theres a multiple changes coming out in the next KC release, would like to ensure the new ingest sdk release works as early as possible.

Update ingest SDK version

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

Release version 2.1.1 on top of master. 
Notable commit difference from 2.1.0 to 2.1.1 is feaa491373527d1a264530ab06f5e3745d1eb585
Other are dependency version upgrade for avro 1.11.1 to 1.11.3

SNOW-947864 Release version 2.1.1

---

src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java

NO-SNOW Make schema evolution add columns idempotent by using if not exists clause

NO-SNOW Make schema evolution add columns idempotent

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

This PR bumps the release version from 2.1.1 to 2.1.2 in the 2.1.1 release branch

v2.1.2 release

---

README.md

Updating readme due to this old [jira](https://snowflakecomputing.atlassian.net/browse/SNOW-88848)

[SNOW-88848] Update readme with Snowflake documentation

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingBufferThreshold.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingUtils.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskStreamingTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java

SNOW-979849
Add offset verification logic as part of channel open. We're verifying that the current start offset = previous end offset +1, if not true, then it potentially means missing or duplicate data. Note that there are some false positives that we can't avoid like when SMT is used, but this is good enough to do blast radius analysis for any corruption issue.

SNOW-979849: Add offset verification logic

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/internal/InternalUtils.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeInternalStage.java
src/test/java/com/snowflake/kafka/connector/internal/InternalStageIT.java
test/perf_test/pom.xml

NO-SNOW
upgrade JDBC to 3.14.5

NO-SNOW: upgrade JDBC to 3.14.5

---

pom.xml
pom_confluent.xml

Copies https://github.com/snowflakedb/snowflake-kafka-connector/pull/797 - merge on behalf of @bansallovish

Upgrade dependency versions

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

Release v2.2.1

---

src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectStreamingClientHandler.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientHandler.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProvider.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/DirectStreamingClientConcurrencyTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/DirectStreamingClientHandlerTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/FakeStreamingClientHandler.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientConcurrencyTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProviderConcurrencyTest.java
src/test/java/net/snowflake/ingest/streaming/FakeSnowflakeStreamingIngestChannel.java
src/test/java/net/snowflake/ingest/streaming/FakeSnowflakeStreamingIngestClient.java

SNOW-1057165 Test-doubles for snowflake-ingest-java
Introduction of test doubles for [snowflake-ingest-java](https://github.com/snowflakedb/snowflake-ingest-java):
- FakeStreamingClientHandler to create clients
- FakeSnowflakeStreamingIngestClient for faking clients
- FakeSnowflakeStreamingIngestChannel for faking channels
This change is test-only except for the automatic extraction of the interface + renaming from the IDE. 
1. Suggested reading order:
Go through the commit list and do them one by one. 
or
2.1 Go through automatic refactoring changes
- StreamingClientHandler -> DirectStreamingClientHandler
- extract interface for StreamingClientHandler
- move method DirectStreamingClientHandler#isClientValid -> StreamingClientHandler#isClientValid
- test rename …

SNOW-1057165  - Test-doubles for snowflake-ingest-java

---

test/test_suit/test_schema_evolution_nullable_values_after_smt.py

SNOW-1055524
Added table schema verification in `TestSchemaEvolutionNullableValuesAfterSmt`.

SNOW-1055524 Check table schema in e2e smt

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

Update to release 2.2.2

---

.github/workflows/End2EndTestConfluent.yml
test/run_test_confluent.sh

SNOW-1269025 - adding verification of confluent Kafka connector on different versions of JRE
Building and unit testing process remains the same (Java8) but e2e testing is run on three different versions of JAVA: 8, 11 and 17. This means that there are 3 times more testing jobs, but they all run in parallel, hence total run time should remain ~the same.
This review is *normal* priority
There are more test jobs hence more chances for tests flakiness. 
No issues with compatibility - test only change

SNOW-1269025 Testing Confluent kafka connector using multiple JRE versions

---

.github/workflows/StressTest.yml

SNOW-1269038 Stress testing Confluent kafka connector using multiple JRE versions
Building and unit testing process remains the same (Java8) but stress testing is run on three different versions of JAVA: 8, 11 and 17. This means that there are 3 times more testing jobs, but they all run in parallel, hence total run time should remain ~the same.
This review is *normal* priority
As confluent tests seems to be stable I see no increased flakyness risk.

SNOW-1269038 Stress testing Confluent kafka connector using multiple JRE versions

---

src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
src/main/java/com/snowflake/kafka/connector/records/RecordService.java
src/main/java/com/snowflake/kafka/connector/records/SnowflakeMetadataConfig.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
src/test/java/com/snowflake/kafka/connector/records/ConverterTest.java
src/test/java/com/snowflake/kafka/connector/records/HeaderTest.java
src/test/java/com/snowflake/kafka/connector/records/MetaColumnTest.java
src/test/java/com/snowflake/kafka/connector/records/ProcessRecordTest.java
src/test/java/com/snowflake/kafka/connector/records/RecordContentTest.java
src/test/java/com/snowflake/kafka/connector/records/ValueSchemaTest.java

SNOW-1056407
A preliminary PR for introducing a new connector timestamp property.

SNOW-1056407 Cleanup metadata properties class. Migrate records tests to junit5

---

src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java

NO-SNOW ticket
Merging community fix by @cmonty-paypal  https://github.com/snowflakedb/snowflake-kafka-connector/pull/834
which expands https://github.com/snowflakedb/snowflake-kafka-connector/pull/734

NO-SNOW Fix idempotent multiple column schema evolution

---

src/main/java/com/snowflake/kafka/connector/records/RecordService.java
src/test/java/com/snowflake/kafka/connector/records/RecordContentTest.java

NO-SNOW Remove unused code path from RecordService
RecordService class parameter `behaviorOnNullValues` is always set to DEFAULT and is not modified in the production code.

NO-SNOW Remove unused code path from RecordService

---

pom.xml
pom_confluent.xml

NO-SNOW
Upgrade to latest ingest-sdk version

NO-SNOW Ugrade to ingest-sdk 2.1.1

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannel.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java

[SNOW-1167007 ](https://snowflakecomputing.atlassian.net/browse/SNOW-1167007)

SNOW-1167007: Migrate schema when receiving null values for not null cols

---

src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/BufferedTopicPartitionChannelTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java

SNOW-1061848
This PR fixes the unit tests for non-buffered scenario - some of them used to still validate the buffered scenario even if it was not expected.

SNOW-1061848: Fix unit tests

---

.github/dependabot.yaml

NO-SNOW Add dependabot
Adding dependabot to the project to track dependencies.
There is no way to handle multiple pom files located in the same directory so the PRs will update only the `pom.xml` file and it is developer responsibility to update `confluent_pom.xml` as well.

NO-SNOW Add dependabot

---

src/main/java/com/snowflake/kafka/connector/internal/parameters/InternalBufferParameters.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProperties.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java

SNOW-1061848
Run `TopicPartitionChannelIT` for a non-buffered scenario.

SNOW-1061848: Run TopicPartitionChannelIT against a non-buffered path

---

src/main/java/com/snowflake/kafka/connector/internal/ColumnInfos.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SchematizationUtils.java
src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/SchematizationUtilsTest.java

NO_SNOW Add column comments from schemaregistry

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
src/main/java/com/snowflake/kafka/connector/internal/PipeProgressRegistryTelemetry.java
src/main/java/com/snowflake/kafka/connector/internal/StageFilesProcessor.java
src/test/java/com/snowflake/kafka/connector/internal/StageFilesProcessorTest.java
src/test/java/com/snowflake/kafka/connector/internal/StageFilesProcessor_FileCategorizerTest.java

SNOW-1019628
This PR enables the V2 cleaner for snowpipe ingestion by default. The parameter was turned on for some customers and for our ongoing test configuration for quite some time now. It was requested to enable it by default.
Next step - remove the parameter and get rid of the "old" cleaner.

SNOW-1019628 Enable V2 file cleaner for Snowpipe ingestion by default

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

Version 2.3.0 will contain all everything before this commit.

Release v2.3.0

---

upload_jar.sh

Script to upload connector package to our /connectors nexus repository - this option would enable downloading custom build onto our k8s cluster, so we can support some local testing scenarios.

NOSNOW: added utility to upload connector to our nexus for simplified k8s deployment

---

src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskForStreamingIT.java
src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java
src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
src/test/java/com/snowflake/kafka/connector/internal/TombstoneRecordIngestionIT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/CloseTopicPartitionChannelIT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2StopIT.java

SNOW-1061851
The PR covers the following changes:
- it runs `SnowflakeSinkServiceV2IT` against a single buffer path
- fixes `DirectTopicPartitionChannel` - one condition was missing there
- runs `SnowflakeSinkServiceV2IT` for OAuth enabled
- `SnowflakeSinkServiceV2StopIT`
- `TombstoneRecordIngestionIT`
- `ConnectionServiceIT`
- `SnowflakeSinkTaskForStreamingIT`
- `CloseTopicPartitionChannelIT`

SNOW-1061851: Run SnowflakeSinkServiceV2IT for a single buffer

---

src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryService.java
src/test/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryServiceTest.java

SNOW-1229110
4 lines for adding telemetry
200 lines for refactoring tests and migrating to JUnit5

SNOW-1229110 Add single buffer usage data to telemetry

---

src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java

SNOW-1541942
Customer using Snowpipe reported random errors thrown at stage and table validations. I believe that we can log details of initialization at INFO level because it happens only on task start. One comment states that initialization happens once for 5 second with up to 120 tries but it is still not a big amount of logs.

SNOW-1541942 Extend Snowpipe initialization logging at INFO level

---

src/test/java/com/snowflake/kafka/connector/ConnectorIT.java
src/test/java/com/snowflake/kafka/connector/SnowflakeSinkTaskForStreamingIT.java
src/test/java/com/snowflake/kafka/connector/UtilsTest.java
src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/DirectStreamingClientHandlerTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2IT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProviderIT.java
src/test/resources/log4j.properties

NO-SNOW Ignore UTs and ITs that connects to SF in order to get OAuth token.
Due to recent changes in security for test users on sfctest0 (including `test_kafka`) Kafka Connector tests started to fail. The reason for this failure is still under investigation.
One of the one client tests ITs is flaky - I disabled it.
The root level logging for tests was changed from `ALL` to `INFO`. The volume of logs produced on `ALL` level was so big that it was impossible to download them and check the reason of failure...

NO-SNOW Ignore OAuth test

---

pom.xml
pom_confluent.xml

NO_SNOW Update dependencies

---

pom.xml
pom_confluent.xml

SNOW-1618257
Required to fix an issue with change_tracking
see https://github.com/snowflakedb/snowflake-ingest-java/releases/tag/v2.2.0

SNOW-1618257 - upgrade to 2.2.0 ingest-sdk

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java

There was no errors reported about closing channels in parallel and we know it's way faster. Let's enable it.

NO-SNOW Enable closing channels in parallel by default

---

src/main/java/com/snowflake/kafka/connector/internal/SnowflakeErrors.java
src/main/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergTableSchemaValidator.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/BaseIcebergIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergTableSchemaValidatorIT.java

SNOW-1658905
Solving most of the TODOs and improving tests a little bit. It's still not a complete feature as it's not plugged into the connector startup.

SNOW-1658905 Improve Iceberg table validations

---

.github/workflows/IntegrationTest.yml
test/build_runtime_jar.sh

SNOW-1658905
Iceberg Integration tests so far are configured only with AWS external volume and breaks in AZURE and GCS.
CI configuration is always taken from the master branch so this chabne can be validated only after merging. Works locally.

SNOW-1658905 Do not run Iceberg tests outside of AWS

---

src/main/java/com/snowflake/kafka/connector/Utils.java
src/main/java/com/snowflake/kafka/connector/internal/DescribeTableRow.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionService.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergTableSchemaValidator.java
src/test/java/com/snowflake/kafka/connector/SnowflakeStreamingSinkTaskBuilder.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergTableSchemaValidatorIT.java
test/build_runtime_jar.sh

SNOW-1658905
Completes iceberg validations by implementing:
- record_metadata data type validation
- plug-in validations into the rest of code
- refactor to run some tasks once per topic
- refactor of calling `describe table` statement
- fix missing $ in bash script

SNOW-1658905 Complete Iceberg validations

---

pom.xml
pom_confluent.xml
test/build_runtime_jar.sh

SNOW-1692725 Profiles to handle AWS specific tests

---

src/main/java/com/snowflake/kafka/connector/internal/streaming/BufferedTopicPartitionChannel.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/InsertErrorMapper.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/SchemaEvolutionTargetItems.java
src/test/java/com/snowflake/kafka/connector/SnowflakeStreamingSinkTaskBuilder.java
src/test/java/com/snowflake/kafka/connector/internal/ConnectionServiceIT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/BufferedTopicPartitionChannelTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/InsertErrorMapperTest.java

SNOW-1694636: Schematization utils refactor (PART 2) - Add mapper for error

---

pom.xml
pom_confluent.xml

Updated avro from 1.11.3 to 1.11.4

Updated avro

---

pom.xml
pom_confluent.xml

[SNOW-1731570] upgrade to 2.3.0 ingest-sdk

---

src/main/java/com/snowflake/kafka/connector/internal/DescribeTableRow.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectStreamingClientHandler.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingClientProperties.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/ColumnInfos.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/ColumnTypeMapper.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergColumnTypeMapper.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/snowflake/SnowflakeColumnTypeMapper.java
src/main/java/com/snowflake/kafka/connector/records/RecordService.java
src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelIT.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/schemaevolution/iceberg/IcebergColumnTypeMapperTest.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/BaseIcebergIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionIT.java

SNOW-1665417 schema evolution primitives

---

src/test/java/com/snowflake/kafka/connector/streaming/iceberg/BaseIcebergIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionNoSchemaEvolutionIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionSchemaEvolutionIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/sql/MetadataRecord.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/sql/PrimitiveJsonRecord.java

SNOW-1692749: Add assertions for records in table

---

.github/workflows/End2EndTestApache.yml
.github/workflows/End2EndTestConfluent.yml
.github/workflows/IntegrationTest.yml
.github/workflows/StressTest.yml
test/cloud_platform.py
test/test_verify.py

SNOW-1728000
This is another intermediate step to a cloud-specific tests. PR contains:
- Removal of unused ENABLE_DELIVERY_GUARANTEE_TESTS
- Fixing a typo GCS -> GCP (Google Cloud Storage vs Google Cloud Platform, trust me I am certified Associate Cloud Engineer)
- Introducing CloudPlatform enum that will be later used for filtering tests

SNOW-1728000 CloudPlatform enum and unused code removal in e2e tests

---

src/main/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryService.java
src/test/java/com/snowflake/kafka/connector/internal/telemetry/SnowflakeTelemetryServiceTest.java

SNOW-1278872
Added jdk version and distribution vendor to metrics

SNOW-1278872 Added jdk version and vendor to metrics

---

pom.xml
pom_confluent.xml

SNOW-00000
Updated junit-bom to 5.11.2

NO-SNOW Updated junit-bom to 5.11.2

---

src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java

NO-SNOW
Fix logging for closing partition channels - partition and topic misplaced

Fix logging for closing partition channels - partition and topic misplaced

---

pom_confluent.xml

Changing the scope as requested by Confluent

NO-SNOW Change kafka-connect-avro-converter scope to provided

---

src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergInitServiceIT.java

Test can be enabled because server side fix was released yesterday.

NO-SNOW Enable IcebergInitServiceIT

---

test/rest_request_template/iceberg_avro_aws.json
test/rest_request_template/iceberg_schema_evolution_avro_aws.json
test/rest_request_template/iceberg_schema_evolution_json_aws.json
test/test_suit/base_iceberg_test.py
test/test_suit/iceberg_avro_aws.py
test/test_suit/iceberg_json_aws.py
test/test_suit/iceberg_schema_evolution_avro_aws.py
test/test_suit/iceberg_schema_evolution_json_aws.py
test/test_suites.py
test/test_verify.py

SNOW-1831140
A couple of small refactors before implementing the tests:
- deleted `"snowflake.streaming.enable.single.buffer": "true"` as it is enabled by default
- created empty test suites for iceberg schema evolution (json/avro)
- moved more dull code to `BaseIcebergTest` cause it will be reused
All of the tests pass locally with ingest sdk from master branch.

SNOW-1831140 Iceberg schema evolution e2e test setup

---

test/test_suit/base_iceberg_test.py
test/test_suit/iceberg_avro_aws.py
test/test_suit/iceberg_schema_evolution_avro_aws.py
test/test_suit/iceberg_schema_evolution_json_aws.py

SNOW-1831140 Complete Iceberg e2e tests

---

pom.xml
pom_confluent.xml

SNOW-XXXXX
Fixes vulnerability in 7.7.0
https://mvnrepository.com/artifact/io.confluent/kafka-schema-registry-client/7.7.0

NO-SNOW Update Confluent dependencies to 7.7.2

---

pom.xml
pom_confluent.xml

NO-SNOW Update jackson and commons-compress

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

NO-SNOW Release 3.0.0

---

src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionSchemaEvolutionIT.java

NO-SNOW
Low hanging fruit.
waitForOffset(i) takes a lot of time. It's not necessary to wait every time record is inserted. This simple change reduced test time from ~13:30 to 8:12 minutes. 
I executed tests a couple of times to make sure they are no flaky.

NO-SNOW speed up Iceberg schema evolution test

---

pom.xml
pom_confluent.xml

SNOW-1826209 Update Confluent to 7.8.0

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

NO-SNOW: Release 3.1.0

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java
src/main/java/com/snowflake/kafka/connector/internal/KCLogger.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeConnectionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeIngestionServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java
src/main/java/com/snowflake/kafka/connector/internal/StageFilesProcessor.java
src/test/java/com/snowflake/kafka/connector/SinkTaskIT.java

Additional logging for snowpipe ingestion method.

NO-SNOW: Additional logging

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java

SNOW-XXXXX
The current default value of 120 seconds was copied from the double buffer settings. However the documentation states 10 seconds for this value... anyway it was decided to set the default for 30 seconds to significantly reduce default latency.

NO-SNOW Set default max_client_lag to 30s

---

pom.xml
pom_confluent.xml

A commit to mark 3.1.1 release

Release 3.1.1

---

pom.xml
pom_confluent.xml

Update snowflake-ingest-sdk to 3.1.0

NO-SNOW Update snowflake-ingest-sdk to 3.1.0

---

src/main/java/com/snowflake/kafka/connector/Utils.java

Missed 3.1.1 version update in a file
follow up to https://github.com/snowflakedb/snowflake-kafka-connector/pull/1053

NO_SNOW - Fix 3.1.1 Release version

---

pom.xml
pom_confluent.xml

Upgrade ingest sdk to 3.1.1

---

pom.xml
pom_confluent.xml

Fixing vulnerability https://avd.aquasec.com/nvd/2025/cve-2025-27496/

NO-SNOW Update snowflake-jdbc to 3.23.1

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

NO-SNOW Update snowflake-ingest-sdk to 3.1.2 / Release 3.1.2

---

pom.xml
pom_confluent.xml
src/test/java/org/apache/kafka/server/fault/MockFaultHandler.java

MockFaultHandler was copied from Kafka code to get rid of NoClassFoundException in ConnectClusterBaseIT https://issues.apache.org/jira/browse/KAFKA-15092

NO-SNOW Update Kafka dependencies to 3.9.0

---

pom.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

This PR marks the 3.1.3 release.

NO-SNOW Release 3.1.3

---

pom_confluent.xml

Fixing inconsistency between pom.xml and pom_confluent.xml

NO-SNOW Fix release 3.1.3

---

.github/workflows/End2EndTestApache.yml
.github/workflows/End2EndTestConfluent.yml
test/run_test_confluent.sh

CONN-10468
Updating the testing version to more recent and dropping Kafka 2.5.1 to limit the number of test permutations.

CONN-10468 Update testing version for Confluent and Kafka

---

src/main/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergDDLTypes.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionNoSchemaEvolutionIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionSchemaEvolutionIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergInitServiceIT.java

SNOW-2043938
Kafka offset is long not integer, so the connector may hit the overflow.

SNOW-2043938 Bugfix - RECORD_METADATA.offset stored as integer

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

A commit to mark 3.2.0 version release

Release 3.2.0

---

pom.xml
pom_confluent.xml

NO-SNOW - Upgrade jdbc-driver to 3.24.2
That PR upgrades the jdbc-driver to  3.24.2
**Auto-merge enabled**

NO-SNOW - Upgrade jdbc-driver to 3.24.2

---

src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/StreamingErrorHandler.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/TopicPartitionChannelTest.java

NO-SNOW Extract error handling logic
Error handling logic is shared across SSv1 and SSv2. Extracting to avoid code duplication.

NO-SNOW Extract error handling logic

---

.github/workflows/GoogleJavaFormat.yml
pom.xml
pom_confluent.xml

Similar change to https://github.com/snowflakedb/snowflake-kafka-connector/pull/1123 but for the master branch.

FLOW-4165 Bump Confluent packages to 7.9.2

---

pom.xml
pom_confluent.xml
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergIngestionSchemaEvolutionIT.java
src/test/java/com/snowflake/kafka/connector/streaming/iceberg/IcebergInitServiceIT.java

Cherry-pick of the change previously merged to `3.2.x` branch
https://github.com/snowflakedb/snowflake-kafka-connector/pull/1130

SNOW-2184975 Remove kafka-schema-rules dependency / fix Iceberg tests

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

This PR marks the 3.2.3 connector release.

SNOW-2184975 Release 3.2.3

---

src/test/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2SchematizationIT.java

Posting this PR to reduce the size of the main SSv2 PR. No functional changes.

CONN-10463 Schematization IT refactor

---

pom.xml
pom_confluent.xml

Cherry-picking from 3.2.x branch: https://github.com/snowflakedb/snowflake-kafka-connector/pull/1136

SNOW-2197881 OSSRH migration (#1136)

---

src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/DefaultStreamingConfigValidator.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/DirectTopicPartitionChannel.java
src/main/java/com/snowflake/kafka/connector/internal/streaming/OpenChannelRetryPolicy.java
src/test/java/com/snowflake/kafka/connector/internal/streaming/OpenChannelRetryPolicyTest.java

Cherry-picking from master branch https://github.com/snowflakedb/snowflake-kafka-connector/pull/1145

SNOW-2227742 Add exponential backoff to handle openChannel errors

---

pom.xml
pom_confluent.xml
src/main/java/com/snowflake/kafka/connector/Utils.java

SNOW-2227742 Release 3.2.4

---

pom.xml
pom_confluent.xml

SNOW-2309653 Update snowflake-jdbc to 3.26.1

---

src/main/java/com/snowflake/kafka/connector/DefaultConnectorConfigValidator.java
src/test/java/com/snowflake/kafka/connector/ConnectorConfigValidatorTest.java

CONN-10560 Do not allow iceberg enabled config option when using SF Streaming SSv2

CONN-10560 Do not allow iceberg enabled config option when using SF Streaming SSv2
